/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devox.GUI.panels;

import com.devox.GUI.tables.DevoxTableModel;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import org.jdesktop.swingx.JXSearchField;

/**
 *
 * @author azaraf
 */
public class Busqueda extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
        searchField = new JXSearchField("Buscar");
        searchField.setSize(700, 35);
        searchField.setInstantSearchDelay(100);
        searchField.setSearchMode(JXSearchField.SearchMode.INSTANT);
        searchField.setLayoutStyle(JXSearchField.LayoutStyle.VISTA);
        searchField.setPromptFontStyle(Font.ITALIC);

        searchField.addActionListener((ActionEvent e) -> {
            searchFieldActionListener(e);
        });
        searchPanel.add(searchField, BorderLayout.WEST);

        

        boolean[] editables = new boolean[]{
            false,
            false,
            false,
            false,
            false
        };

        

        modelClientes = new DevoxTableModel(DevoxTableModel.columnasEnBusqueda, editables);
        modelClientes.agregarTabla(scrollClientes);
        modelLotes = new DevoxTableModel(DevoxTableModel.columnasEnBusqueda, editables);
        modelLotes.agregarTabla(scrollLotes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scrollClientes = new javax.swing.JScrollPane();
        scrollLotes = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(250, 250, 250));
        jTabbedPane1.addTab("Clientes", scrollClientes);
        jTabbedPane1.addTab("Lotes", scrollLotes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Busqueda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JScrollPane scrollLotes;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables
    private JXSearchField searchField;
    private org.inspira.devox.services.queries.Busqueda search = new org.inspira.devox.services.queries.Busqueda();
    private DevoxTableModel modelClientes;
    private DevoxTableModel modelLotes;

    private void searchFieldActionListener(ActionEvent e) {
        if (jTabbedPane1.getSelectedComponent().equals(scrollClientes)) {
            modelClientes.getTabla().removeAll();
            modelClientes.llenarDeDatos(buscarPorCliente("%" +searchField.getText().toUpperCase()+"%"));

        }
        if (jTabbedPane1.getSelectedComponent().equals(scrollLotes)) {
            modelLotes.getTabla().removeAll();
            modelLotes.llenarDeDatos(buscarPorLote("%" + searchField.getText().toUpperCase() + "%"));
        }
    }

    private Object[][] buscarPorLote(String lote) {
        Object[][] objs;
        objs = search.porLote(lote);
        
        return objs;
    }

    private Object[][] buscarPorCliente(String cliente) {
        Object[][] objs;
        objs = search.porCliente(cliente);

        return objs;
    }

}
