/*
 * To change this license header, choose
 @Override
 public boolean accept(File f) {
 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
 }

 @Override
 public String getDescription() {
 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
 }
 License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devox.GUI.panels;

import com.devox.GUI.Actions;
import com.devox.GUI.PDF.CrearReporteApto;
import com.devox.GUI.PDF.CrearReporteDestruccion;
import com.devox.GUI.panels.forms.NuevoProducto;
import com.devox.GUI.tables.DevoxTableModel;
import com.devox.LOG.Admin.OptionPanels;
import com.devox.LOG.Admin.EscarnearCodigoDeBarras;
import com.devox.LOG.Entidades.Configuraciones;
import com.devox.LOG.Entidades.ContenidoDevolucion;
import com.devox.LOG.Funciones;
import com.devox.LOG.cuadricula.ListaCuadriculas;
import com.devox.LOG.cuadricula.ListaCuadriculasTarima;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import org.inspira.devox.logger.Log;
import org.inspira.devox.services.MakeDevolucion;
import org.inspira.devox.services.devolucion.AccionesSubDivision;
import org.inspira.devox.services.devolucion.AccionesTransporte;
import org.inspira.devox.services.organico.AccionesAlmacen;
import org.inspira.devox.services.organico.AccionesTarima;
import org.inspira.devox.services.productos.AccionesHistorialPrecio;
import org.inspira.devox.shared.Almacen;
import org.inspira.devox.shared.HistorialPrecio;
import org.inspira.devox.shared.Motivo;
import org.inspira.devox.shared.Shareable;
import org.inspira.devox.shared.SubDivision;
import org.inspira.devox.shared.Tarima;
import org.inspira.devox.shared.Transporte;

/**
 *
 * @author azaraf
 */
public class CapturaDevolucion extends javax.swing.JPanel {

    public CapturaDevolucion(ContenidoDevolucion content, Actions padre) {
        this.content = content;
        this.padre = padre;
        folio = content.getDevolucion().getFolio();
        myInitComponents();
        devolucionProductos = new OptionPanels(content, model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameDetalles = new javax.swing.JFrame();
        panelDetalles = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        detallesFolio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        detallesCliente = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        detallesSucursal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        detallesFamilia = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        detallesFechaRecibido = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        detallesFolioCliente = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        detallesFolioAbbott = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        detallesFacturaCliente = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        detallesDivision = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        detallesMotivo = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        detallesTarima = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        detallesFechaCaptura = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        detallesMontoTotal = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        detallesStatus = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        detallesDestino = new javax.swing.JLabel();
        botonCerrarDetalles = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        frameEscaner = new javax.swing.JFrame();
        panelEscaner = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        campoCodigoDeBarras = new javax.swing.JTextField();
        botonTerminarDeEscanear = new javax.swing.JButton();
        botonNuevoProducto = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        editarVentana = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        editMotivo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        boton71 = new javax.swing.JRadioButton();
        boton71M = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editFolioCliente = new javax.swing.JTextField();
        editFolioAbbott = new javax.swing.JTextField();
        editFactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        editObservaciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        editAlmacen = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        editCajas = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        editTransporte = new javax.swing.JComboBox();
        editCodigoRazon = new javax.swing.ButtonGroup();
        jLabelFolio = new javax.swing.JLabel();
        panelFolio = new javax.swing.JLabel();
        panelCliente = new javax.swing.JLabel();
        panelSucursal = new javax.swing.JLabel();
        panelFecha = new javax.swing.JFormattedTextField();
        botonVerDetalles = new javax.swing.JButton();
        panelOpciones = new javax.swing.JPanel();
        panelAddItem = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JLabel();
        panelRemoveItem = new javax.swing.JPanel();
        botonEliminar = new javax.swing.JLabel();
        panelTarima = new javax.swing.JPanel();
        botonTarima = new javax.swing.JLabel();
        panelCerrarCaptura = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JLabel();
        panelImprimir = new javax.swing.JPanel();
        botonImprimir = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        labelMonto = new javax.swing.JLabel();
        labelCantidadTota = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        frameDetalles.setTitle("Detalles del folio");
        frameDetalles.setBackground(new java.awt.Color(250, 250, 250));
        frameDetalles.setMinimumSize(new java.awt.Dimension(375, 530));
        frameDetalles.setSize(new java.awt.Dimension(860, 530));

        panelDetalles.setBackground(new java.awt.Color(250, 250, 250));
        panelDetalles.setLayout(new java.awt.GridLayout(15, 2, 3, 5));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Folio");
        panelDetalles.add(jLabel9);

        detallesFolio.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesFolio.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesFolio);

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Cliente");
        panelDetalles.add(jLabel11);

        detallesCliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesCliente.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesCliente);

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Sucursal");
        panelDetalles.add(jLabel13);

        detallesSucursal.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesSucursal.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesSucursal);

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("División");
        panelDetalles.add(jLabel15);

        detallesFamilia.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesFamilia.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesFamilia);

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Fecha de recibido");
        panelDetalles.add(jLabel19);

        detallesFechaRecibido.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesFechaRecibido.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesFechaRecibido);

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Folio de cliente");
        panelDetalles.add(jLabel21);

        detallesFolioCliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesFolioCliente.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesFolioCliente);

        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Folio Abbott");
        panelDetalles.add(jLabel26);

        detallesFolioAbbott.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesFolioAbbott.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesFolioAbbott);

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Factura del cliente");
        panelDetalles.add(jLabel17);

        detallesFacturaCliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesFacturaCliente.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesFacturaCliente);

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Código de razón");
        panelDetalles.add(jLabel29);

        detallesDivision.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesDivision.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesDivision);

        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Motivo de devolución");
        panelDetalles.add(jLabel31);

        detallesMotivo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesMotivo.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesMotivo);

        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Tarima");
        panelDetalles.add(jLabel33);

        detallesTarima.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesTarima.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesTarima);

        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Fecha de captura");
        panelDetalles.add(jLabel35);

        detallesFechaCaptura.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesFechaCaptura.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesFechaCaptura);

        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Monto total de la devolución");
        panelDetalles.add(jLabel37);

        detallesMontoTotal.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        detallesMontoTotal.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesMontoTotal);

        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Estado");
        panelDetalles.add(jLabel38);

        detallesStatus.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        detallesStatus.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesStatus);

        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Destino");
        panelDetalles.add(jLabel39);

        detallesDestino.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        detallesDestino.setForeground(new java.awt.Color(9, 91, 173));
        panelDetalles.add(detallesDestino);

        botonCerrarDetalles.setText("Cerrar");
        botonCerrarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarDetallesActionPerformed(evt);
            }
        });

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameDetallesLayout = new javax.swing.GroupLayout(frameDetalles.getContentPane());
        frameDetalles.getContentPane().setLayout(frameDetallesLayout);
        frameDetallesLayout.setHorizontalGroup(
            frameDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(frameDetallesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCerrarDetalles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frameDetallesLayout.setVerticalGroup(
            frameDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerrarDetalles)
                    .addComponent(jButton1)))
        );

        frameEscaner.setAlwaysOnTop(true);
        frameEscaner.setMinimumSize(new java.awt.Dimension(220, 220));
        frameEscaner.setSize(new java.awt.Dimension(220, 260));
        frameEscaner.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                frameEscanerWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        panelEscaner.setBackground(new java.awt.Color(250, 250, 250));
        panelEscaner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 5, true));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/barcode.png"))); // NOI18N

        jLabel30.setText("<html>Escanea el código de barras del producto</html>");

        campoCodigoDeBarras.setFont(new java.awt.Font("Courier", 0, 18)); // NOI18N
        campoCodigoDeBarras.setForeground(new java.awt.Color(53, 53, 53));
        campoCodigoDeBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCodigoDeBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCodigoDeBarrasKeyTyped(evt);
            }
        });

        botonTerminarDeEscanear.setText("Dejar de capturar");
        botonTerminarDeEscanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarDeEscanearActionPerformed(evt);
            }
        });

        botonNuevoProducto.setText("Agregar nuevo producto");
        botonNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEscanerLayout = new javax.swing.GroupLayout(panelEscaner);
        panelEscaner.setLayout(panelEscanerLayout);
        panelEscanerLayout.setHorizontalGroup(
            panelEscanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscanerLayout.createSequentialGroup()
                .addGroup(panelEscanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEscanerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelEscanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCodigoDeBarras)
                            .addGroup(panelEscanerLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(botonTerminarDeEscanear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEscanerLayout.setVerticalGroup(
            panelEscanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscanerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCodigoDeBarras, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonTerminarDeEscanear, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameEscanerLayout = new javax.swing.GroupLayout(frameEscaner.getContentPane());
        frameEscaner.getContentPane().setLayout(frameEscanerLayout);
        frameEscanerLayout.setHorizontalGroup(
            frameEscanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscaner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameEscanerLayout.setVerticalGroup(
            frameEscanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscaner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setCurrentDirectory(new java.io.File("/Reportes/"));
        jFileChooser1.setDialogTitle("Guardar detalles de Devox-Nueva devolución");
        jFileChooser1.setSelectedFile(new java.io.File("/Folio_"+ content.getFolioDHL() +".pdf"));

        editarVentana.setSize(new java.awt.Dimension(380, 471));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de recibido");

        editDate.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setText("Motivo");

        jLabel3.setText("Código de Razón:");

        editCodigoRazon.add(boton71);
        boton71.setText("71");

        boton71M.setText("71-M");

        jLabel4.setText("Folio Cliente");

        jLabel5.setText("Folio Abbott");

        jLabel6.setText("Factura");

        jLabel7.setText("Observaciones");

        jLabel8.setText("Almacén");

        jLabel10.setText("Cajas");

        editCajas.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel12.setText("Transporte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(editDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(editMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(boton71)
                                .addGap(51, 51, 51)
                                .addComponent(boton71M))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editFolioCliente)
                                    .addComponent(editFolioAbbott)
                                    .addComponent(editFactura)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(editCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editObservaciones))))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boton71)
                    .addComponent(boton71M))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editFolioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editFolioAbbott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(editFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(editObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(editCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(editTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout editarVentanaLayout = new javax.swing.GroupLayout(editarVentana.getContentPane());
        editarVentana.getContentPane().setLayout(editarVentanaLayout);
        editarVentanaLayout.setHorizontalGroup(
            editarVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editarVentanaLayout.setVerticalGroup(
            editarVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 5, true));

        jLabelFolio.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabelFolio.setText("Folio DHL");

        panelFolio.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        panelFolio.setForeground(new java.awt.Color(9, 91, 173));

        panelCliente.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        panelSucursal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelSucursal.setForeground(new java.awt.Color(51, 51, 51));
        panelSucursal.setText(" ");

        panelFecha.setEditable(false);
        panelFecha.setBackground(new java.awt.Color(250, 250, 250));
        panelFecha.setBorder(null);
        panelFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.FULL))));
        panelFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        panelFecha.setFocusable(false);
        panelFecha.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        botonVerDetalles.setText("Ver detalles >>");
        botonVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerDetallesActionPerformed(evt);
            }
        });

        panelOpciones.setBackground(new java.awt.Color(250, 250, 250));
        panelOpciones.setLayout(new java.awt.GridLayout(1, 4, 5, 3));

        panelAddItem.setBackground(new java.awt.Color(9, 91, 173));

        botonAgregar.setForeground(new java.awt.Color(250, 250, 250));
        botonAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniadd.png"))); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAgregarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAgregarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelAddItemLayout = new javax.swing.GroupLayout(panelAddItem);
        panelAddItem.setLayout(panelAddItemLayout);
        panelAddItemLayout.setHorizontalGroup(
            panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAddItemLayout.setVerticalGroup(
            panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOpciones.add(panelAddItem);

        panelRemoveItem.setBackground(new java.awt.Color(220, 102, 102));

        botonEliminar.setForeground(new java.awt.Color(250, 250, 250));
        botonEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minidelete.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelRemoveItemLayout = new javax.swing.GroupLayout(panelRemoveItem);
        panelRemoveItem.setLayout(panelRemoveItemLayout);
        panelRemoveItemLayout.setHorizontalGroup(
            panelRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoveItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRemoveItemLayout.setVerticalGroup(
            panelRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoveItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOpciones.add(panelRemoveItem);

        panelTarima.setBackground(new java.awt.Color(9, 91, 173));

        botonTarima.setForeground(new java.awt.Color(250, 250, 250));
        botonTarima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonTarima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minitarima.png"))); // NOI18N
        botonTarima.setText("<html>Cambiar tarima</html>");
        botonTarima.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTarima.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonTarima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTarimaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonTarimaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonTarimaMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelTarimaLayout = new javax.swing.GroupLayout(panelTarima);
        panelTarima.setLayout(panelTarimaLayout);
        panelTarimaLayout.setHorizontalGroup(
            panelTarimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonTarima)
                .addContainerGap())
        );
        panelTarimaLayout.setVerticalGroup(
            panelTarimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonTarima)
                .addContainerGap())
        );

        if (!content.getDestino()){

            panelOpciones.add(panelTarima);
        }

        panelCerrarCaptura.setBackground(new java.awt.Color(9, 91, 173));

        botonCerrar.setForeground(new java.awt.Color(250, 250, 250));
        botonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minisave.png"))); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarCapturaLayout = new javax.swing.GroupLayout(panelCerrarCaptura);
        panelCerrarCaptura.setLayout(panelCerrarCapturaLayout);
        panelCerrarCapturaLayout.setHorizontalGroup(
            panelCerrarCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarCapturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCerrarCapturaLayout.setVerticalGroup(
            panelCerrarCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarCapturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOpciones.add(panelCerrarCaptura);

        panelImprimir.setBackground(new java.awt.Color(9, 91, 173));

        botonImprimir.setForeground(new java.awt.Color(250, 250, 250));
        botonImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniprint.png"))); // NOI18N
        botonImprimir.setText("Imprimir");
        botonImprimir.setToolTipText("");
        botonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonImprimirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonImprimirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonImprimirMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelImprimirLayout = new javax.swing.GroupLayout(panelImprimir);
        panelImprimir.setLayout(panelImprimirLayout);
        panelImprimirLayout.setHorizontalGroup(
            panelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImprimirLayout.setVerticalGroup(
            panelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOpciones.add(panelImprimir);

        scrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPanel.setAutoscrolls(true);
        scrollPanel.getHorizontalScrollBar().setUnitIncrement(20);
        scrollPanel.getVerticalScrollBar().setUnitIncrement(20);

        labelMonto.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelMonto.setForeground(new java.awt.Color(9, 91, 173));
        labelMonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMonto.setText("    ");

        labelCantidadTota.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelCantidadTota.setForeground(new java.awt.Color(9, 91, 173));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelSucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerDetalles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFolio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelFecha))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelCantidadTota, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollPanel))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFolio)
                        .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVerDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSucursal)
                .addGap(12, 12, 12)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMonto)
                        .addComponent(labelCantidadTota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        panelFecha.setText(hoy);
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoDeBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodigoDeBarrasKeyTyped
        char c = evt.getKeyChar();
        if (c == '\n') {
            if (checarCodigoDeBarras(campoCodigoDeBarras.getText(), 1)) {
                rows++;

            }
            campoCodigoDeBarras.setText(null);
        }
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_campoCodigoDeBarrasKeyTyped

    private void botonTerminarDeEscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarDeEscanearActionPerformed
        frameEscaner.setVisible(false);
    }//GEN-LAST:event_botonTerminarDeEscanearActionPerformed

    private void botonVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDetallesActionPerformed
        frameDetalles.setVisible(true);
    }//GEN-LAST:event_botonVerDetallesActionPerformed

    private void botonCerrarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarDetallesActionPerformed
        frameDetalles.setVisible(false);
    }//GEN-LAST:event_botonCerrarDetallesActionPerformed

    private void botonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseEntered
        panelAddItem.setBackground(blanco);
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniadd_inv.png")));
        botonAgregar.setForeground(azul);
    }//GEN-LAST:event_botonAgregarMouseEntered

    private void botonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseExited
        panelAddItem.setBackground(azul);
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniadd.png")));
        botonAgregar.setForeground(blanco);
    }//GEN-LAST:event_botonAgregarMouseExited

    private void botonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseClicked
        fireEscaner();
    }//GEN-LAST:event_botonAgregarMouseClicked

    private void botonTarimaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTarimaMouseEntered
        panelTarima.setBackground(blanco);
        botonTarima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minitarima_inv.png")));
        botonTarima.setForeground(azul);
    }//GEN-LAST:event_botonTarimaMouseEntered

    private void botonTarimaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTarimaMouseExited
        panelTarima.setBackground(azul);
        botonTarima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minitarima.png")));
        botonTarima.setForeground(blanco);
    }//GEN-LAST:event_botonTarimaMouseExited

    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseEntered
        panelCerrarCaptura.setBackground(blanco);
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minisave_inv.png")));
        botonCerrar.setForeground(azul);
    }//GEN-LAST:event_botonCerrarMouseEntered

    private void botonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseExited
        panelCerrarCaptura.setBackground(azul);
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minisave.png")));
        botonCerrar.setForeground(blanco);
    }//GEN-LAST:event_botonCerrarMouseExited

    private void botonImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseEntered
        panelImprimir.setBackground(blanco);
        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniprint_inv.png")));
        botonImprimir.setForeground(azul);
    }//GEN-LAST:event_botonImprimirMouseEntered

    private void botonImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseExited
        panelImprimir.setBackground(azul);
        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniprint.png")));
        botonImprimir.setForeground(blanco);
    }//GEN-LAST:event_botonImprimirMouseExited

    private void botonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseEntered
        panelRemoveItem.setBackground(blanco);
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minidelete_inv.png")));
        botonEliminar.setForeground(rojo);
    }//GEN-LAST:event_botonEliminarMouseEntered

    private void botonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseExited
        panelRemoveItem.setBackground(rojo);
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minidelete.png")));
        botonEliminar.setForeground(blanco);
    }//GEN-LAST:event_botonEliminarMouseExited

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        cerrarCaptura();
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonTarimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTarimaMouseClicked
        cambiarTarima();
    }//GEN-LAST:event_botonTarimaMouseClicked

    private void botonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseClicked
        int value = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de querer eliminar este\n"
                + "dato definitivamente? ",
                "Eliminar datos",
                JOptionPane.YES_NO_OPTION);
        if (value == JOptionPane.YES_OPTION) {
            int[] rowsSelected = model.getTabla().getSelectedRows();
            for (int i : rowsSelected) {
                model.removeRow(i);
            }
        }

    }//GEN-LAST:event_botonEliminarMouseClicked

    private void botonImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseClicked
        if (cerrarCaptura()) {
            imprimir();
        }

    }//GEN-LAST:event_botonImprimirMouseClicked

    private void botonNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoProductoActionPerformed
        campoCodigoDeBarras.setText(null);
        NuevoProducto np = new NuevoProducto();
        np.setVisible(true);
    }//GEN-LAST:event_botonNuevoProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        editarVentana.setVisible(true);
        editar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        editarVentana.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MakeDevolucion mk = new MakeDevolucion();
        content.setFechaRecibido(editDate.getDate());
        content.setMotivo(Integer.parseInt(editMotivo.getSelectedItem().toString()));
        content.setCodigoRazon(getSelectedButtonText(editCodigoRazon));
        content.setFolioCliente(editFolioCliente.getText());
        content.setFolioAbbott(editFolioAbbott.getText());
        content.setFactura(editFactura.getText());
        content.setObservaciones(editObservaciones.getText());
        content.setAlmacen(editAlmacen.getSelectedItem().toString());
        content.setCajas((Integer) editCajas.getValue());
        for (Transporte m : mk.getTransportes()) {
            if (m.getDescripcion().equals(editTransporte.getSelectedItem().toString())) {
                content.setTransporte(m.getCodigo());
            }
        }
        content.setTransporte(editTransporte.getSelectedItem().toString());
        editarVentana.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void frameEscanerWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameEscanerWindowGainedFocus
        campoCodigoDeBarras.selectAll();
    }//GEN-LAST:event_frameEscanerWindowGainedFocus


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boton71;
    private javax.swing.JRadioButton boton71M;
    private javax.swing.JLabel botonAgregar;
    private javax.swing.JLabel botonCerrar;
    private javax.swing.JButton botonCerrarDetalles;
    private javax.swing.JLabel botonEliminar;
    private javax.swing.JLabel botonImprimir;
    private javax.swing.JButton botonNuevoProducto;
    private javax.swing.JLabel botonTarima;
    private javax.swing.JButton botonTerminarDeEscanear;
    private javax.swing.JButton botonVerDetalles;
    private javax.swing.JTextField campoCodigoDeBarras;
    private javax.swing.JLabel detallesCliente;
    private javax.swing.JLabel detallesDestino;
    private javax.swing.JLabel detallesDivision;
    private javax.swing.JLabel detallesFacturaCliente;
    private javax.swing.JLabel detallesFamilia;
    private javax.swing.JLabel detallesFechaCaptura;
    private javax.swing.JLabel detallesFechaRecibido;
    private javax.swing.JLabel detallesFolio;
    private javax.swing.JLabel detallesFolioAbbott;
    private javax.swing.JLabel detallesFolioCliente;
    private javax.swing.JLabel detallesMontoTotal;
    private javax.swing.JLabel detallesMotivo;
    private javax.swing.JLabel detallesStatus;
    private javax.swing.JLabel detallesSucursal;
    private javax.swing.JLabel detallesTarima;
    private javax.swing.JComboBox editAlmacen;
    private javax.swing.JSpinner editCajas;
    private javax.swing.ButtonGroup editCodigoRazon;
    private com.toedter.calendar.JDateChooser editDate;
    private javax.swing.JTextField editFactura;
    private javax.swing.JTextField editFolioAbbott;
    private javax.swing.JTextField editFolioCliente;
    private javax.swing.JComboBox editMotivo;
    private javax.swing.JTextField editObservaciones;
    private javax.swing.JComboBox editTransporte;
    private javax.swing.JFrame editarVentana;
    private javax.swing.JFrame frameDetalles;
    private javax.swing.JFrame frameEscaner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFolio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCantidadTota;
    private javax.swing.JLabel labelMonto;
    private javax.swing.JPanel panelAddItem;
    private javax.swing.JPanel panelCerrarCaptura;
    private javax.swing.JLabel panelCliente;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JPanel panelEscaner;
    private javax.swing.JFormattedTextField panelFecha;
    private javax.swing.JLabel panelFolio;
    private javax.swing.JPanel panelImprimir;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelRemoveItem;
    private javax.swing.JLabel panelSucursal;
    private javax.swing.JPanel panelTarima;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
    private String hoy;
    private ContenidoDevolucion content;
    private DevoxTableModel model;
    private OptionPanels devolucionProductos;
    private final Color blanco = new Color(250, 250, 250);
    private final Color azul = new Color(9, 91, 173);
    private final Color rojo = new Color(220, 102, 102);
    private int rows = 0;
    private float montoTotal = 0;
    private int cantidadTotal = 0;
    private Actions padre;
    private int folio;
    private JTable tabla;
    private final JPopupMenu popupMenu = new JPopupMenu();
    private JMenuItem agregarItem;
    private int posicionX;
    private int posicionY;
    private Tarima tarimaActual;
    public static boolean bandera = false;
    private final ImageIcon iconNegro = new ImageIcon(getClass().getResource("/com/devox/GUI/images/tarimita_black.png"));

    private void myInitComponents() {
        hoy = Funciones.getFechaCompleta(content.getFechaCaptura());
        initComponents();
        panelFolio.setText(content.getFolioDHL());
        panelCliente.setText(content.getNombreCliente());
        panelSucursal.setText(content.getNombreSucursal() + ", " + content.getClaveCliente());
        detallesFolio.setText(content.getFolioDHL());
        detallesCliente.setText(content.getNombreCliente());
        detallesSucursal.setText(content.getNombreSucursal() + ", " + content.getClaveCliente());
        detallesFamilia.setText(content.getDivisionCliente());
        detallesFechaRecibido.setText(Funciones.getFechaCompleta(content.getFechaRecibido()));
        detallesFolioCliente.setText(content.getFolioCliente());
        detallesFolioAbbott.setText(content.getFolioAbbott());
        detallesFacturaCliente.setText(content.getFactura());
        detallesDivision.setText(content.getCodigoRazon());
        detallesMotivo.setText(String.valueOf(content.getMotivo().getCodigo()) + ", " + content.getMotivo().getDescripcion());
        detallesFechaCaptura.setText(Funciones.getFechaCompleta(content.getFechaCaptura()));
        detallesMontoTotal.setText("$" + String.format("%,.2f", montoTotal));
        detallesStatus.setText(content.getEstado().getNombre());
        if (content.getDestino()) {
            detallesDestino.setText("Apto");
            detallesTarima.setText("Sin tarima");
        } else {
            detallesDestino.setText("Destrucción");
            detallesTarima.setText(content.getTarimaNombre() + ", " + content.getDivisionCliente());
        }

        setTable();

    }

    private void fireEscaner() { // 1
        frameEscaner.setVisible(true);
    }

    private boolean checarCodigoDeBarras(String CB, int cantidad) {
        Log.print("Checando el CodigoBarras " + CB + ", cantidad " + cantidad + ", ");
        com.devox.LOG.Admin.EscarnearCodigoDeBarras ecdb = new EscarnearCodigoDeBarras(CB, cantidad, content, this);
        if (ecdb.isSuccess()) {
            com.devox.LOG.Entidades.Producto p = ecdb.getProducto();
            if (!content.getDestino()) {
                p.setIdTarima(content.getTarima().getIdTarima());
                p.setTarimaNombre(content.getTarimaNombre());
            }
            devolucionProductos.agregarProducto(p);
            return true;
        }
        return false;
    }

    private boolean cerrarCaptura() {
        boolean hasProducto = false;
        if (!devolucionProductos.isEmpty()) {
            content.altaNuevaDevolucion(); // Pone la información de la devolución en la BD
            devolucionProductos.cerrarCaptura();
            padre.guardarDevolucion(content);
            ListaDeDevoluciones.agregarNuevaDevolucion(folio);
            hasProducto = true;
            ListaCuadriculas.actualizarTotal();
            ListaCuadriculasTarima.actualizarTotal();
        } else {
            JOptionPane.showMessageDialog(null, "No puede guardar ninguna devolución sin productos");
        }
        
        return hasProducto;
    }

    private void imprimir() {
        content.updateEstado();

        String f = String.format("%06d", folio);

        if (content.getDestino()) {
            String fac = content.getFactura();
            String fc = content.getFolioCliente();
            String cs = content.getSucursal().getCodigoSucursal() + ", " + content.getNombreCliente() + " - " + content.getSucursal().getNombre();
            List<List<Object>> listadelistas = new ArrayList<>();
            for (int i = 0; i < model.getRowCount(); i++) {
                List<Object> l = new ArrayList<>();
                l.add(model.getValueAt(i, 1));
                l.add(model.getValueAt(i, 2));
                l.add(model.getValueAt(i, 3));
                l.add(model.getValueAt(i, 5));
                l.add(model.getValueAt(i, 4));
                listadelistas.add(l);
            }
            Object[][] dat = new Object[listadelistas.size()][];
            for (int i = 0; i < listadelistas.size(); i++) {
                dat[i] = listadelistas.get(i).toArray();
            }

            CrearReporteApto pdf = new CrearReporteApto(f, fac, fc, cs, "" + content.getMotivo().getCodigo() + ", " + content.getMotivo().getDescripcion(), dat);
            File file = new File(new Configuraciones().getPath() + "/Folio_" + f + ".pdf");

            pdf.crear(file);
            JOptionPane.showMessageDialog(null, "Documento guardado!");
        } else {
            CrearReporteDestruccion pdf = new CrearReporteDestruccion(model, content, content.getSucursal().getFamilia_idFamilia());
            File file = new File(new Configuraciones().getPath() + "/Folio_" + f + ".pdf");
            pdf.crear(file);
        }
        Log.print("Guardado en PDF!");
    }

    private void setTable() {
        if (content.getDestino()) {
            model = new DevoxTableModel(
                    DevoxTableModel.columnsApto,
                    new boolean[]{
                        false,
                        false,
                        false,
                        false,
                        true,
                        true,
                        false
                    });

        } else {
            model = new DevoxTableModel(
                    DevoxTableModel.columnsDestruccion,
                    new boolean[]{
                        false,
                        false,
                        false,
                        false,
                        true,
                        true,
                        false,
                        false
                    }
            );

        }
        model.agregarTabla(scrollPanel);
        model.addTableModelListener((TableModelEvent e) -> {
            if (e.getType() == TableModelEvent.INSERT) {
                //añadió una nueva fila
                actualizarMontoTotal();
            }
            if (e.getType() == TableModelEvent.UPDATE) {
                //cambió datos de una fila
                int r = e.getFirstRow();
                int c = e.getColumn();
                if (c == 5) {
                    //float pre = (devolucionProductos.getProducto(r).getPrecioSeleccionado());
                    devolucionProductos.getProducto(r).setCantidad(((Integer) model.getValueAt(r, 5)));
                    model.setValueAt(devolucionProductos.getProducto(r).getMonto(), r, 6);
                }

                if (c == 6) {
                    actualizarMontoTotal();
                }

                if (c == 4) {
                    float newPrice = (float) model.getValueAt(r, 4);
                    Log.print("precio modificado a: " + newPrice);
                    String ean = model.getValueAt(r, 0).toString();
                    String idProducto = model.getValueAt(r, 1).toString();
                    int change = JOptionPane.NO_OPTION;
                    change = JOptionPane.showConfirmDialog(
                            null,
                            "¿Desea cambiar este precio en la Base de Datos?",
                            "Cambio de precio",
                            JOptionPane.YES_NO_OPTION
                    );
                    if (change == JOptionPane.YES_OPTION) {
                        changePrice(newPrice, ean, idProducto);
                    }

                    devolucionProductos.getProducto(r).setPrecioSeleccionado(newPrice);
                    devolucionProductos.getProducto(r).setCantidad(((Integer) model.getValueAt(r, 5)));
                    model.setValueAt(((Integer) model.getValueAt(r, 5) * (float) model.getValueAt(r, 4)), r, 6);
                    actualizarMontoTotal();
                }
            }
            if (e.getType() == TableModelEvent.DELETE) {
                //borró filas de la tabla
                devolucionProductos.eliminarProducto(e.getFirstRow());
                actualizarMontoTotal();
            }

        });
    }

    private void actualizarMontoTotal() {
        montoTotal = 0;
        cantidadTotal = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            montoTotal += (float) model.getValueAt(i, 6);
            cantidadTotal += (Integer) model.getValueAt(i, 5);
        }
        labelMonto.setText("$" + String.format("%.2f", montoTotal));
        detallesMontoTotal.setText("$" + String.format("%.2f", montoTotal));
        labelCantidadTota.setText(String.valueOf(cantidadTotal) + " productos");
    }

    public String getIdSucursal() {
        return content.getSucursal().getCodigoSucursal();
    }

    private void cambiarTarima() {
        String nombre;
        int destfiscal;
        String almacen;
        Integer[] selectionValues = new Integer[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
        List<String> almacenes = new ArrayList<>();
        AccionesAlmacen aa = new AccionesAlmacen();
        aa.loadDatabaseInstances();
        for (Shareable s : aa.getEntityInstances()) {
            almacenes.add(((Almacen) s).getCv());
        }
        nombre = (String) JOptionPane.showInputDialog(null, "Nombre de la nueva tarima:", "Nueva tarima", JOptionPane.OK_OPTION, iconNegro, null, null);
        if (!nombre.equals("null")) {
            Object df = JOptionPane.showInputDialog(
                    null,
                    "Folio de destrucción fiscal:",
                    "Nueva tarima",
                    JOptionPane.OK_OPTION,
                    iconNegro,
                    selectionValues,
                    selectionValues[0]
            );
            if (df != null) {
                destfiscal = (Integer) df;
                almacen = (String) JOptionPane.showInputDialog(null, "Almacén", "Nueva tarima", JOptionPane.OK_OPTION, iconNegro, almacenes.toArray(), almacenes.toArray()[0]);
                if (!almacen.equals("null")) {
                    AccionesTarima t = new AccionesTarima();
                    t.setNombre(nombre);
                    t.setAlmacen_cv(almacen);
                    t.setFolioDestruccionFiscal(destfiscal);
                    t.alta();
                    t.loadDatabaseInstances();

                    Tarima mTarima = new Tarima();
                    mTarima.setAlmacen_cv(almacen);
                    mTarima.setNombre(nombre);
                    mTarima.setIdTarima(t.grabIdTarimaByNombre(nombre));
                    // CAMBIAR EL ID DE LA TARIMA
                    content.setTarima(mTarima);
                }
            }

        }
    }

    public void setTarimaActual(Tarima tarimaActual) {
        this.tarimaActual = tarimaActual;
    }

    public ContenidoDevolucion getContent() {
        return content;
    }

    public void changePrice(float precio, String ean, String idProducto) {
        Log.print("precio: $" + String.format("%.2f", precio));
        Log.print("EAN: " + ean);
        Log.print("Producto: " + idProducto);
        Log.print("Sucursal: " + content.getSucursal().getCodigoSucursal());

        AccionesHistorialPrecio ahp = new AccionesHistorialPrecio();
        ahp.loadDatabaseInstances();
        int x = -1;
        Shareable[] s = ahp.getEntityInstances();
        for (int i = 0; i < s.length; i++) {
            HistorialPrecio price = (HistorialPrecio) s[i];
            if (ean.equals(price.getEan())
                    && idProducto.equals(price.getIdProducto())
                    && content.getSucursal().getCodigoSucursal().equals(price.getIdSucursal())) {
                x = i;
                break;
            }
        }
        ahp.setPrecio(precio);
        ahp.setEan(ean);
        ahp.setIdProducto(idProducto);
        ahp.setIdSucursal(content.getSucursal().getCodigoSucursal());
        ahp.setPosition(x);
        ahp.cambio();
    }

    private void editar() {
        editDate.setDate(content.getFechaRecibido());
        MakeDevolucion mk = new MakeDevolucion();
        int itemSelected = 0;
        int i = 0;
        for (Motivo m : mk.getMotivos()) {
            editMotivo.addItem(m.getCodigo());
            if (content.getMotivo().getCodigo() == m.getCodigo()) {
                itemSelected = i;
            }
            i++;
        }
        editMotivo.setSelectedIndex(itemSelected);
        if (content.getCodRazon().getCodigo() == 1) {
            editCodigoRazon.setSelected(boton71.getModel(), true);
        } else {
            editCodigoRazon.setSelected(boton71M.getModel(), true);
        }
        editFolioCliente.setText(content.getFolioCliente());
        editFolioAbbott.setText(content.getFolioAbbott());
        editFactura.setText(content.getFactura());
        editObservaciones.setText(content.getObservaciones());
        AccionesAlmacen aAlmacen = new AccionesAlmacen();
        i = 0;
        aAlmacen.loadDatabaseInstances();
        for (Shareable a : aAlmacen.getEntityInstances()) {
            editAlmacen.addItem(((Almacen) a).getCv());
            if (content.getAlmacen().equals(((Almacen) a).getCv())) {
                itemSelected = i;
            }
            i++;
        }
        editAlmacen.setSelectedIndex(itemSelected);
        editCajas.setValue(content.getCajas());
        AccionesTransporte aTransporte = new AccionesTransporte();
        aTransporte.loadDatabaseInstances();
        i = 0;
        for (Shareable s : aTransporte.getEntityInstances()) {
            editTransporte.addItem(((Transporte) s).getDescripcion());
            if (content.getTransporte().equals(((Transporte) s).getDescripcion())) {
                itemSelected = i;
            }
            i++;
        }
        editTransporte.setSelectedIndex(itemSelected);
    }

    public int getSelectedButtonText(ButtonGroup buttonGroup) {
        AccionesSubDivision codigosDeRazones = new AccionesSubDivision();
        codigosDeRazones.loadDatabaseInstances();
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                for (SubDivision s : codigosDeRazones.getSubDivisiones()) {
                    if (button.getText().equals(s.getSubDivision())) {
                        return s.getCodigo();
                    }
                }
            }
        }
        return 0;
    }
}
