/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devox.GUI.panels;

import com.devox.GUI.PDF.CrearReporteTarimas;
import com.devox.GUI.tables.DevoxTableModel;
import com.devox.LOG.Entidades.Configuraciones;
import com.devox.LOG.Funciones;
import org.inspira.devox.logger.Log;
import java.awt.Color;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import org.inspira.devox.services.organico.AccionesAlmacen;
import org.inspira.devox.services.organico.AccionesTarima;
import org.inspira.devox.services.queries.LayoutTarima;
import org.inspira.devox.shared.Almacen;
import org.inspira.devox.shared.Shareable;

/**
 *
 * @author azaraf
 */
public class CuadriculaTarima extends javax.swing.JPanel implements Comparable<CuadriculaTarima>{

    private boolean flagAbierta;
    private String nameTarima = "Nombre tarima";
    private String almacen = "Almacén";
    public String division = "División";
    public int folioDestruccionFiscal = 0;
    public Date fechaApertura = null;
    public Date fechaCierre = null;
    public String id;
    public int index;
    private Object[][] obj;
    private List<String> listaAlmacenes;
    private AccionesTarima axTarima;

    /**
     * Creates new form Cuadricula
     */
    public CuadriculaTarima() {
        initComponents();
    }

    public CuadriculaTarima(String name, Date fechaApertura, Date fechaCierre, int id) {
        this.fechaCierre = fechaCierre;
        this.index = id;
        this.id = String.valueOf(id);
        this.fechaApertura = fechaApertura;
        LayoutTarima layoutTarimas = new LayoutTarima();
        obj = layoutTarimas.obtenerLayout(name);
        axTarima = new AccionesTarima();
        
        this.nameTarima = name;
        initComponents();
        this.jLabelId.setText(this.id);
        if (this.obj.length != 0) {
            this.botonVerMas.setEnabled(true);
            this.labelFill.setText(null);
            this.jButton1.setVisible(false);
            this.division = "";
            String[] divisiones = axTarima.divisionesTarima(name);
            for(int i = 0; i < divisiones.length; i++){
                this.division = this.division.concat(divisiones[i]);
                if(i != divisiones.length -1)
                    this.division = this.division.concat(", ");
            }
            this.folioDestruccionFiscal = (Integer) obj[0][4];
            this.almacen = obj[0][1].toString();
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                fechaApertura = sdf.parse(this.obj[0][2].toString());

            } catch (ParseException ex) {
                Log.print(ex);
            }
        }

        setInformation();
        if (fechaCierre != null) {
            panelCerrarCaptura.setVisible(false);
        }
        
        listaAlmacenes = new ArrayList<>();
        AccionesAlmacen almacenes = new AccionesAlmacen();
        almacenes.loadDatabaseInstances();
        for (Shareable a : almacenes.getEntityInstances()) {
            listaAlmacenes.add(((Almacen) a).getCv());
        }
    }

    public boolean getjCheckBox1() {
        return jCheckBox1.isSelected();
    }

    public void setjCheckBox1(boolean pos) {
        jCheckBox1.setSelected(pos);
        if (pos) {
            this.setBackground(colorSelected);
        } else {
            this.setBackground(colorUnselected);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informacion = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        infoNombre = new javax.swing.JLabel();
        infoAlmacen = new javax.swing.JLabel();
        infoFolioDHL = new javax.swing.JLabel();
        panelFecha = new javax.swing.JFormattedTextField();
        scrollPanel = new javax.swing.JScrollPane();
        infoEstado = new javax.swing.JLabel();
        infoDestruccion = new javax.swing.JLabel();
        panelFecha1 = new javax.swing.JFormattedTextField();
        infoDivision = new javax.swing.JLabel();
        infoCantidad = new javax.swing.JLabel();
        panelOpciones1 = new javax.swing.JPanel();
        panelCerrarCaptura = new javax.swing.JPanel();
        infoBotonCerrar = new javax.swing.JLabel();
        panelImprimir = new javax.swing.JPanel();
        botonImprimir = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        infoBotonEditar = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreTarimaForm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboAlmacenes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        comboDexFiscal = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        labelFill = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelTarima = new javax.swing.JLabel();
        labelDivision = new javax.swing.JLabel();
        labelFechaApertura = new javax.swing.JLabel();
        botonVerMas = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        labelFechaCierre = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        Informacion.setExtendedState(2);
        Informacion.setSize(new java.awt.Dimension(1134, 669));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        infoNombre.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        infoNombre.setText("Nombre");

        infoAlmacen.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        infoAlmacen.setForeground(new java.awt.Color(51, 51, 51));
        infoAlmacen.setText("Almacén");

        infoFolioDHL.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        infoFolioDHL.setForeground(new java.awt.Color(9, 91, 173));
        infoFolioDHL.setText("0000");

        panelFecha.setEditable(false);
        panelFecha.setBackground(new java.awt.Color(250, 250, 250));
        panelFecha.setBorder(null);
        panelFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.FULL))));
        panelFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        panelFecha.setFocusable(false);
        panelFecha.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        panelFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelFechaActionPerformed(evt);
            }
        });

        scrollPanel.setAutoscrolls(true);

        infoEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/tarimita_blue.png"))); // NOI18N
        infoEstado.setText("Estado");
        infoEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoEstado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        infoDestruccion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        infoDestruccion.setForeground(new java.awt.Color(51, 51, 51));
        infoDestruccion.setText("Destrucción Fiscal");

        panelFecha1.setEditable(false);
        panelFecha1.setBackground(new java.awt.Color(250, 250, 250));
        panelFecha1.setBorder(null);
        panelFecha1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.FULL))));
        panelFecha1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        panelFecha1.setFocusable(false);
        panelFecha1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        infoDivision.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        infoDivision.setForeground(new java.awt.Color(51, 51, 51));
        infoDivision.setText("División");

        infoCantidad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        infoCantidad.setForeground(new java.awt.Color(51, 51, 51));
        infoCantidad.setText("Cantidad");

        panelOpciones1.setBackground(new java.awt.Color(250, 250, 250));
        panelOpciones1.setLayout(new java.awt.GridLayout(1, 4, 5, 3));

        panelCerrarCaptura.setBackground(new java.awt.Color(9, 91, 173));

        infoBotonCerrar.setForeground(new java.awt.Color(250, 250, 250));
        infoBotonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minisave.png"))); // NOI18N
        infoBotonCerrar.setText("Cerrar");
        infoBotonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoBotonCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        infoBotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBotonCerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBotonCerrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBotonCerrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarCapturaLayout = new javax.swing.GroupLayout(panelCerrarCaptura);
        panelCerrarCaptura.setLayout(panelCerrarCapturaLayout);
        panelCerrarCapturaLayout.setHorizontalGroup(
            panelCerrarCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarCapturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoBotonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCerrarCapturaLayout.setVerticalGroup(
            panelCerrarCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarCapturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoBotonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOpciones1.add(panelCerrarCaptura);

        panelImprimir.setBackground(new java.awt.Color(9, 91, 173));

        botonImprimir.setForeground(new java.awt.Color(250, 250, 250));
        botonImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniprint.png"))); // NOI18N
        botonImprimir.setText("Imprimir");
        botonImprimir.setToolTipText("");
        botonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonImprimirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonImprimirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonImprimirMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelImprimirLayout = new javax.swing.GroupLayout(panelImprimir);
        panelImprimir.setLayout(panelImprimirLayout);
        panelImprimirLayout.setHorizontalGroup(
            panelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImprimirLayout.setVerticalGroup(
            panelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOpciones1.add(panelImprimir);

        panelEditar.setBackground(new java.awt.Color(9, 91, 173));

        infoBotonEditar.setForeground(new java.awt.Color(250, 250, 250));
        infoBotonEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniedit.png"))); // NOI18N
        infoBotonEditar.setText("<html>Editar</html>");
        infoBotonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoBotonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        infoBotonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBotonEditarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBotonEditarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBotonEditarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoBotonEditar)
                .addContainerGap())
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoBotonEditar)
                .addContainerGap())
        );

        panelOpciones1.add(panelEditar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelOpciones1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelFecha1)
                            .addComponent(panelFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoDestruccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(infoNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(infoFolioDHL, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                .addGap(117, 117, 117))
                            .addComponent(infoEstado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoAlmacen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(infoDivision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)))
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoNombre)
                            .addComponent(infoFolioDHL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoDivision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoAlmacen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoDestruccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(scrollPanel))
                .addContainerGap())
        );

        javax.swing.GroupLayout InformacionLayout = new javax.swing.GroupLayout(Informacion.getContentPane());
        Informacion.getContentPane().setLayout(InformacionLayout);
        InformacionLayout.setHorizontalGroup(
            InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InformacionLayout.setVerticalGroup(
            InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setSelectedFile(new java.io.File("/Tarima_"+ nameTarima +".pdf"));

        jFrame1.setSize(new java.awt.Dimension(350, 280));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setText("Nombre de la tarima:");

        jLabel2.setText("Almacén:");

        comboAlmacenes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Destrucción fiscal:");

        comboDexFiscal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreTarimaForm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(comboAlmacenes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(comboDexFiscal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreTarimaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAlmacenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboDexFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        setMaximumSize(new java.awt.Dimension(267, 357));
        setPreferredSize(new java.awt.Dimension(866, 127));
        setSize(new java.awt.Dimension(866, 127));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        labelFill.setFont(new java.awt.Font("Lucida Grande", 1, 31)); // NOI18N
        labelFill.setForeground(new java.awt.Color(9, 92, 173));
        labelFill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFill.setText("vacía");

        labelEstado.setForeground(new java.awt.Color(51, 51, 51));
        labelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/tarimita_black.png"))); // NOI18N
        labelEstado.setText("Estado");
        labelEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelEstado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        labelTarima.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelTarima.setText("<html>Nombre</html>");

        labelDivision.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelDivision.setForeground(new java.awt.Color(102, 102, 102));
        labelDivision.setText("Division");

        labelFechaApertura.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelFechaApertura.setForeground(new java.awt.Color(9, 92, 173));
        labelFechaApertura.setText("00/00/2015");

        botonVerMas.setText("Ver más");
        botonVerMas.setEnabled(false);
        botonVerMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMasActionPerformed(evt);
            }
        });

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        labelFechaCierre.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelFechaCierre.setForeground(new java.awt.Color(50, 50, 50));
        labelFechaCierre.setText("00/00/2015");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelEstado)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFechaApertura, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(labelFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(labelTarima, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerMas)
                        .addGap(245, 245, 245)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFill, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelFill)
                        .addComponent(labelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelFechaApertura)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelFechaCierre))
                        .addComponent(labelTarima))
                    .addComponent(labelDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVerMas)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        setjCheckBox1(checked);
        checked = !checked;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        setjCheckBox1(checked);
        checked = !checked;
    }//GEN-LAST:event_formMouseClicked

    private void botonVerMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMasActionPerformed
        Informacion.setVisible(true);

    }//GEN-LAST:event_botonVerMasActionPerformed

    private void panelFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelFechaActionPerformed

    private void botonImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseExited
        panelImprimir.setBackground(azu);
        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniprint.png")));
        botonImprimir.setForeground(colorUnselected);
    }//GEN-LAST:event_botonImprimirMouseExited

    private void botonImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseEntered
        panelImprimir.setBackground(colorUnselected);
        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniprint_inv.png")));
        botonImprimir.setForeground(azu);
    }//GEN-LAST:event_botonImprimirMouseEntered

    private void infoBotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBotonCerrarMouseClicked
        //cerrarCaptura();
        AccionesTarima at = new AccionesTarima();
        at.cerrarTarima(nameTarima);
        JOptionPane.showMessageDialog(this, "Se cerró la tarima " + nameTarima + " hoy a las " + new SimpleDateFormat("hh:mm").format(new Date()) + " horas");
        panelCerrarCaptura.setVisible(false);
    }//GEN-LAST:event_infoBotonCerrarMouseClicked

    private void infoBotonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBotonCerrarMouseExited
        panelCerrarCaptura.setBackground(azu);
        infoBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minisave.png")));
        infoBotonCerrar.setForeground(colorUnselected);
    }//GEN-LAST:event_infoBotonCerrarMouseExited

    private void infoBotonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBotonCerrarMouseEntered
        panelCerrarCaptura.setBackground(colorUnselected);
        infoBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/minisave_inv.png")));
        infoBotonCerrar.setForeground(azu);
    }//GEN-LAST:event_infoBotonCerrarMouseEntered

    private void botonImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseClicked
        Log.print("Guardado en PDF!");
        CrearReporteTarimas pdf = new CrearReporteTarimas(nameTarima, obj);
        pdf.crear(new File(new Configuraciones().getPath() + "/Tarima_" + nameTarima + ".pdf"));
        JOptionPane.showMessageDialog(null, "Documento guardado!");
    }//GEN-LAST:event_botonImprimirMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar esta tarima?", "Eliminar Tarima", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new AccionesTarima().baja(id);
            JOptionPane.showMessageDialog(null, "Tarima Eliminada. Verá los cambios al actualizar la lista");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void infoBotonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBotonEditarMouseClicked
        jFrame1.setVisible(true);
        nombreTarimaForm.setText(nameTarima);
        comboAlmacenes.setModel(new DefaultComboBoxModel(listaAlmacenes.toArray(new String[0])));
        comboAlmacenes.setSelectedItem(almacen);
        comboDexFiscal.setSelectedItem(folioDestruccionFiscal);
    }//GEN-LAST:event_infoBotonEditarMouseClicked

    private void infoBotonEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBotonEditarMouseExited
        panelEditar.setBackground(azu);
        infoBotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniedit.png")));
        infoBotonEditar.setForeground(colorUnselected);

    }//GEN-LAST:event_infoBotonEditarMouseExited

    private void infoBotonEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBotonEditarMouseEntered
        panelEditar.setBackground(colorUnselected);
        infoBotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/miniedit_inv.png")));
        infoBotonEditar.setForeground(azu);
    }//GEN-LAST:event_infoBotonEditarMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.nameTarima = nombreTarimaForm.getText();
        this.almacen = comboAlmacenes.getSelectedItem().toString();
        this.folioDestruccionFiscal = Integer.parseInt(comboDexFiscal.getSelectedItem().toString());
        axTarima.cambio(nameTarima, almacen, comboDexFiscal.getSelectedItem().toString(), id);
        labelTarima.setText(nameTarima);
        infoFolioDHL.setText(nameTarima);
        infoAlmacen.setText("Almacén: " + almacen);
        infoDestruccion.setText("Destrucción fiscal: " + folioDestruccionFiscal);
        jFrame1.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Informacion;
    private javax.swing.JLabel botonImprimir;
    private javax.swing.JButton botonVerMas;
    private javax.swing.JComboBox comboAlmacenes;
    private javax.swing.JComboBox comboDexFiscal;
    private javax.swing.JLabel infoAlmacen;
    private javax.swing.JLabel infoBotonCerrar;
    private javax.swing.JLabel infoBotonEditar;
    private javax.swing.JLabel infoCantidad;
    private javax.swing.JLabel infoDestruccion;
    private javax.swing.JLabel infoDivision;
    private javax.swing.JLabel infoEstado;
    private javax.swing.JLabel infoFolioDHL;
    private javax.swing.JLabel infoNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDivision;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFechaApertura;
    private javax.swing.JLabel labelFechaCierre;
    private javax.swing.JLabel labelFill;
    private javax.swing.JLabel labelTarima;
    private javax.swing.JTextField nombreTarimaForm;
    private javax.swing.JPanel panelCerrarCaptura;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JFormattedTextField panelFecha;
    private javax.swing.JFormattedTextField panelFecha1;
    private javax.swing.JPanel panelImprimir;
    private javax.swing.JPanel panelOpciones1;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
    private boolean checked = false;
    private Date fecha;
    private final Color neg = new Color(50, 50, 50); // Color negro
    private final Color azu = new Color(9, 91, 173); // Color azul
    private final Color roj = new Color(255, 102, 102); // Color rojo
    private final Color ver = new Color(102, 204, 0); // Color verde
    private final Color colorSelected = new Color(220, 235, 255); // Color azul claro
    private final Color colorUnselected = new Color(250, 250, 250); // Color blanco

    private final ImageIcon iconVerde = new ImageIcon(getClass().getResource("/com/devox/GUI/images/tarimita_green.png"));
    private final ImageIcon iconRojo = new ImageIcon(getClass().getResource("/com/devox/GUI/images/tarimita_red.png"));
    private final ImageIcon iconAzul = new ImageIcon(getClass().getResource("/com/devox/GUI/images/tarimita_blue.png"));
    private final ImageIcon iconNegro = new ImageIcon(getClass().getResource("/com/devox/GUI/images/tarimita_black.png"));
    private DevoxTableModel model;
    private JTable tabla;

    public Date getFecha() {
        return fecha;
    }

    public String getNameTarima() {
        return nameTarima;
    }

    private void setInformation() {
        labelFechaApertura.setText(fechaApertura != null ? Funciones.getFechaCompleta(fechaApertura) : "");
        labelFechaCierre.setText(fechaCierre != null ? Funciones.getFechaCompleta(fechaCierre) : "");
        labelTarima.setText(nameTarima);
        labelDivision.setText(division);
        labelEstado.setText(fechaCierre == null ? "Abierta" : "Cerrada");
        labelEstado.setIcon(fechaCierre == null ? iconAzul : iconNegro);
        labelEstado.setForeground(fechaCierre == null ? azu : neg);
        panelFecha.setText(fechaApertura != null ? "Abierta el " + Funciones.getFechaCompleta(fechaApertura) : "");
        panelFecha1.setText(fechaCierre != null ? "Cerrada el " + Funciones.getFechaCompleta(fechaCierre) : "");
        infoFolioDHL.setText(nameTarima);
        infoDivision.setText("División: " + division);
        infoAlmacen.setText("Almacén: " + almacen);
        infoEstado.setText(fechaCierre == null ? "Abierta" : "Cerrada");
        infoEstado.setForeground(fechaCierre == null ? azu : neg);
        infoEstado.setIcon(fechaCierre == null ? iconAzul : iconNegro);
        infoDestruccion.setText("Destrucción fiscal: " + folioDestruccionFiscal);
        tabla();
    }

    private void tabla() {
        Object[][] newobj = new Object[obj.length][4];
        for (int i = 0; i < obj.length; i++) {
            newobj[i][0] = String.format("%06d", (Integer) obj[i][5]);
            newobj[i][1] = obj[i][6];
            newobj[i][2] = obj[i][7];
            newobj[i][3] = obj[i][8];
        }
        boolean[] editables = new boolean[]{false, false, false, false};
        model = new DevoxTableModel(DevoxTableModel.columnsReporteTarimas, editables);
        model.agregarTabla(scrollPanel);
        model.llenarDeDatos(newobj);
        model.addTableModelListener((TableModelEvent e) -> {
            if (e.getType() == TableModelEvent.INSERT) {
                actualizaCantidad();
            }
        });

    }

    private void actualizaCantidad() {
        infoCantidad.setText("Cantidad: " + getSuma());
    }

    private String getSuma() {
        long sum = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            sum += (Long) model.getValueAt(i, 3);
        }
        return String.valueOf(sum);
    }

    @Override
    public int compareTo(CuadriculaTarima o) {
        int compareFolio = ((CuadriculaTarima) o).index;
        return compareFolio - this.index;
    }
    
    
}
