/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devox.GUI.panels;

import com.devox.GUI.Actions;
import com.devox.LOG.Entidades.ContenidoDevolucion;
import devox.DAO.ClienteDAO;
import devox.DAO.DAO;
import devox.database.DBC;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author azaraf
 */
public class NuevaDevolucion extends javax.swing.JPanel {

    private int folio;
    private ContenidoDevolucion contenido;
    private Actions parent;

//    /**
//     * Crea nuevo formulario para iniciar una devolución
//     *
//     * @param contenido - Detalles de la devolucion
//     */
//    public NuevaDevolucion(ContenidoDevolucion contenido, Actions parent) {
//        this.contenido = contenido;
//        this.folio = contenido.getFolio();
//        this.parent = parent;
//        
//        myInitComponents();
//    }
    public NuevaDevolucion(Actions parent) {
        this.folio = 0;
        this.parent = parent;
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupDivisiones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        labelFamilia1 = new javax.swing.JLabel();
        labelSucursal1 = new javax.swing.JLabel();
        labelCliente1 = new javax.swing.JLabel();
        panelDetalles = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboMotivos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        textFolioAbbot = new javax.swing.JTextField();
        textDocumento = new javax.swing.JTextField();
        textFactura = new javax.swing.JTextField();
        textTarima = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textObservaciones = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        cajasSpinner = new javax.swing.JSpinner();
        panelDivisiones = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelMotivo = new javax.swing.JLabel();
        dateChooserRecibido = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        panelPrincipal.setBackground(new java.awt.Color(250, 250, 250));
        panelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelHeader.setBackground(new java.awt.Color(250, 250, 250));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setText("Folio DHL");

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/devoluciongrey.png"))); // NOI18N
        jLabel1.setText("Segregación");
        jLabel1.setIconTextGap(12);

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jSeparator5))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelCliente.setBackground(new java.awt.Color(250, 250, 250));

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBox1.setAutoscrolls(true);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        labelFamilia1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelFamilia1.setForeground(new java.awt.Color(102, 102, 102));
        labelFamilia1.setText("<html>División</html>");

        labelSucursal1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelSucursal1.setForeground(new java.awt.Color(102, 102, 102));
        labelSucursal1.setText("<html>Nombre de la sucursal</html>");

        labelCliente1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        labelCliente1.setText("<html>Nombre del cliente o razón social</html>");

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSucursal1)
                    .addComponent(labelCliente1)
                    .addComponent(jComboBox1, 0, 409, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(labelFamilia1)
                .addContainerGap())
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSucursal1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFamilia1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelDetalles.setBackground(new java.awt.Color(250, 250, 250));

        jLabel15.setText("Fecha de recibido");

        jLabel13.setText("Motivo");

        comboMotivos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMotivosItemStateChanged(evt);
            }
        });

        jLabel5.setText("Almacén");

        //jComboBox2.setSelectedIndex(3);

        jScrollPane1.setBackground(new java.awt.Color(250, 250, 250));

        textObservaciones.setColumns(20);
        textObservaciones.setLineWrap(true);
        textObservaciones.setRows(5);
        textObservaciones.setWrapStyleWord(true);
        textObservaciones.setOpaque(false);
        jScrollPane1.setViewportView(textObservaciones);

        jLabel16.setText("Cajas");

        cajasSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        panelDivisiones.setBackground(new java.awt.Color(250, 250, 250));
        panelDivisiones.setLayout(new java.awt.GridLayout(3, 1, 4, 0));

        jLabel3.setText("Código de Razón");
        panelDivisiones.add(jLabel3);

        labelMotivo.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        labelMotivo.setForeground(new java.awt.Color(53, 53, 53));

        dateChooserRecibido.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(comboMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(panelDetallesLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(13, 13, 13)))
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDivisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetallesLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(cajasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFolioAbbot, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textTarima, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panelDivisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(textFolioAbbot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTarima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jLabel6.setText(getCodigoReferencia());

        jLabel4.setText(getCodigoDestruccion());

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonContinuar.setText("Continuar");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 368, Short.MAX_VALUE)
                        .addComponent(botonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonContinuar))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonContinuar))
                .addGap(18, 18, 18))
        );

        jLabel8.setText("Estos códigos de calidad aparecerán en la parte inferior del reporte impreso:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
//        String data = jComboBox1.getSelectedItem().toString();
//        try {
//            String[] info = data.split(" — ");
//            search(info[0]);
//            clienteSeleccionado = info[0];
//        } catch (Exception e) {
//            Log.print(e);
//        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void comboMotivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMotivosItemStateChanged
//        for (Motivo m : mk.getMotivos()) {
//            if (m.getCodigo() == (Integer) comboMotivos.getSelectedItem()) {
//                labelMotivo.setText(m.getDescripcion());
//                textObservaciones.setText(m.getDescripcion());
//            }
//        }
    }//GEN-LAST:event_comboMotivosItemStateChanged

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        if (comprobar()) {
            capturar();
        }
    }//GEN-LAST:event_botonContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JSpinner cajasSpinner;
    private javax.swing.JComboBox comboMotivos;
    private com.toedter.calendar.JDateChooser dateChooserRecibido;
    private javax.swing.ButtonGroup groupDivisiones;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelCliente1;
    private javax.swing.JLabel labelFamilia1;
    private javax.swing.JLabel labelMotivo;
    private javax.swing.JLabel labelSucursal1;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JPanel panelDivisiones;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField textDocumento;
    private javax.swing.JTextField textFactura;
    private javax.swing.JTextField textFolioAbbot;
    private javax.swing.JTextArea textObservaciones;
    private javax.swing.JTextField textTarima;
    // End of variables declaration//GEN-END:variables

//    private MakeDevolucion mk;
    private List<Integer> listaIdMotivos;
//    private List<String> listaIdTransporte;
//    private List<String> listaIdDivisiones;
////    private SucursalView fCliente;
////    private AccionesDevolucion dev;
//    private boolean clienteCorrecto = false;
////    private AccionesSubDivision codigosDeRazones;
//    final static Color ERROR_COLOR = Color.PINK;
//    private int idStatus;
//    private Date fechaRecibido;
//    private Date fechaCaptura;
//    private int idMotivo;
//    private String folioAbbott;
//    private String folioCliente;
//    private String factura;
//    private String clienteSeleccionado;
//    private int cajas;
//    private int idSubDivision;
//    private String observaciones;
//    private String idTransporte;
//    private List<String> items = new ArrayList<>();
//    private String tarimaNombre;
//    private int tarimaDestruccion;
//    private String tarimaAlmacen;
//    private List<String> listaAlmacenes;
////    private AccionesAlmacen almacenes;
////    private AccionesFamilia divisiones;
////    private Tarima mTarima;
//    private boolean flagPanelDestino = false;

    private boolean comprobar() {
//        idStatus = 1;
//        fechaCaptura = new Date();
//        fechaRecibido = dateChooserRecibido.getDate();
//        idMotivo = Integer.parseInt(comboMotivos.getSelectedItem().toString());
//        folioAbbott = textFolioAbbot.getText();
//        folioCliente = textDocumento.getText();
//        factura = textFactura.getText();
//        cajas = (Integer) cajasSpinner.getValue();
//        idSubDivision = getSelectedButtonText(groupDivisiones);
//        observaciones = textObservaciones.getText();
//        idTransporte = null;
//
//        if (fechaRecibido == null || fechaRecibido.after(fechaCaptura)) {
//            JOptionPane.showMessageDialog(
//                    null,
//                    "El campo \"Fecha de devolución\" no puede estar vacío. o después de hoy.",
//                    "Campos erroneos",
//                    JOptionPane.OK_OPTION);
//            return false;
//        }
//
//        if (!clienteCorrecto || clienteSeleccionado == null) {
//            JOptionPane.showMessageDialog(
//                    null,
//                    "La sucursal del cliente es incorrecta",
//                    "Campos erroneos",
//                    JOptionPane.OK_OPTION);
//            return false;
//        }
//        if (idSubDivision == 0) {
//            JOptionPane.showMessageDialog(
//                    null,
//                    "Debe seleccionar una subdivisión (71 o 71-M).",
//                    "Campos vacíos",
//                    JOptionPane.OK_OPTION);
//            return false;
//        }
//
////        for (Transporte m : mk.getTransportes()) {
////            if (m.getDescripcion().equals(comboTransporte.getSelectedItem().toString())) {
////                idTransporte = m.getCodigo();
////            }
////        }
//        tarimaAlmacen = jComboBox2.getSelectedItem().toString();
//        if (!flagPanelDestino) { // Si está en NEL, haces un set de tarima.
//            Log.print("Setting the Tarima");
//            tarimaNombre = textTarima.getText();
//            if (tarimaNombre.isEmpty()) {
//                Log.print("El nombre de la tarima está vacío");
//                JOptionPane.showMessageDialog(
//                        null,
//                        "Debe dar un nombre válido a la tarima.",
//                        "Campos vacíos",
//                        JOptionPane.OK_OPTION);
//                return false;
//            }
////            AccionesTarima t = new AccionesTarima();
////            t.setNombre(tarimaNombre);
////            t.setAlmacen_cv(tarimaAlmacen);
////            t.setFolioDestruccionFiscal(tarimaDestruccion);
////            t.alta();
////            t.loadDatabaseInstances();
////            mTarima = new Tarima();
////            mTarima.setAlmacen_cv(tarimaAlmacen);
////            mTarima.setNombre(tarimaNombre);
////            mTarima.setIdTarima(t.grabIdTarimaByNombre(tarimaNombre));
//        }
//        
//        if(observaciones.isEmpty()){
//            JOptionPane.showMessageDialog(
//                    null,
//                    "Debe de indicar Observaciones.",
//                    "Campos vacíos",
//                    JOptionPane.OK_OPTION);
//            return false;
//        }
//
        return true;
    }

    /**
     * Datos que se obtienen de esta ventana: folio (foliodhl), estado, destino
     * (apto, dx) nombre cliente, sucursal,
     */
    private void capturar() {
//        contenido.setFolioCliente(folioCliente);
//        contenido.setFolioAbbott(folioAbbott);
//        contenido.setFactura(factura);
//        contenido.setFechaCaptura(fechaCaptura);
//        contenido.setFechaRecibido(fechaRecibido);
//        contenido.setDestino(flagPanelDestino);
//        contenido.setEstado(idStatus);
////        contenido.setSucursal(fCliente.getCodigoSucursal());
//        contenido.setMotivo(idMotivo);
//        contenido.setCodigoRazon(idSubDivision);
//        contenido.setObservaciones(observaciones);
//        contenido.setCajas(cajas);
//        
////        if (flagPanelDestino) {
////            contenido.setTarima(null);
////            contenido.setAlmacen(tarimaAlmacen);
////        } else {
////            Log.print("La tarima");
////            contenido.setTarima(mTarima);
////            contenido.setAlmacen(tarimaAlmacen);
////        }
//        
//        parent.capturarProductos(contenido);
    }

    public int getSelectedButtonText(ButtonGroup buttonGroup) {
//        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
//            AbstractButton button = buttons.nextElement();
//
//            if (button.isSelected()) {
//                for (SubDivision s : codigosDeRazones.getSubDivisiones()) {
//                    if (button.getText().equals(s.getSubDivision())) {
//                        return s.getCodigo();
//                    }
//                }
//            }
//        }
        return 0;
    }

    private void myInitComponents() {
        initComponents();

        //MotivoDAO mD = new MotivoDAO();
        ClienteDAO clienteDAO = new ClienteDAO();
        List<List> listaClientes = clienteDAO.loadData();
        
        if(listaClientes == null){
               System.out.println("es nulo");
        }
        else{
            System.out.println("No es nulo");
        }
//        codigosDeRazones = new AccionesSubDivision();
//        divisiones = new AccionesFamilia();
//        almacenes = new AccionesAlmacen();
        //listaIdMotivos = mD.loadData().get(1);
//        listaIdDivisiones = new ArrayList<>();
//        listaAlmacenes = new ArrayList<>();
//
//        for (Motivo m : mk.getMotivos()) {
//            listaIdMotivos.add(m.getCodigo());
//        }
//
//        listaIdTransporte = new ArrayList<>();
//        for (Transporte m : mk.getTransportes()) {
//            listaIdTransporte.add(m.getDescripcion());
//        }
//        divisiones.loadDatabaseInstances();
//        for (Shareable m : divisiones.getEntityInstances()) {
//            listaIdDivisiones.add(((Familia) m).getCodigoFamilia());
//        }
//        almacenes.loadDatabaseInstances();
//        for (Shareable a : almacenes.getEntityInstances()) {
//            listaAlmacenes.add(((Almacen) a).getCv());
//        }
//        AccionesSucursal suc = new AccionesSucursal();
//        suc.loadDatabaseInstances();
//        items.add("");
//        items = new AccionesSucursal().listaDeSucursales();
//
//        AutoCompleteDecorator.decorate(jComboBox1);
//
//        labelFolio1.setText(String.format("%06d", folio));
//
//        for (SubDivision iter : codigosDeRazones.getSubDivisiones()) {
//            JCheckBox checkBox = new JCheckBox(iter.getSubDivision());
//            groupDivisiones.add(checkBox);
//            panelDivisiones.add(checkBox);
//        }
        PromptSupport.setPrompt("Folio del Cliente", textDocumento);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, textDocumento);
        PromptSupport.setPrompt("Folio de Abbott", textFolioAbbot);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, textFolioAbbot);
        PromptSupport.setPrompt("Factura", textFactura);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, textFactura);
        PromptSupport.setPrompt("Tarima", textTarima);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, textTarima);
        PromptSupport.setPrompt("Observaciones", textObservaciones);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, textObservaciones);
        dateChooserRecibido.setDate(new Date());

    }

    private void search(String cli) {
//        fCliente = new SucursalView(cli);
//
//        if (fCliente.getNombreSucursal() == null) {
//            labelCliente1.setText(Funciones.setText("Nombre del cliente o razón social", Funciones.ALIGN_LEFT));
//            labelSucursal1.setText(Funciones.setText("Sucursal", Funciones.ALIGN_LEFT));
//            labelFamilia1.setText(Funciones.setText("Familia", Funciones.ALIGN_LEFT));
//            clienteCorrecto = false;
//
//        } else {
//            labelCliente1.setText(Funciones.setText(fCliente.getNombreCliente(), Funciones.ALIGN_LEFT));
//            labelCliente1.setToolTipText(fCliente.getNombreCliente());
//            labelSucursal1.setText(Funciones.setText(fCliente.getNombreSucursal(), Funciones.ALIGN_LEFT));
//            labelCliente1.setToolTipText(fCliente.getNombreCliente());
//            labelFamilia1.setText(Funciones.setText(fCliente.getFamilia(), Funciones.ALIGN_LEFT));
//            labelCliente1.setToolTipText(fCliente.getFamilia());
//            clienteCorrecto = true;
//        }

    }

    private String getCodigoDestruccion() {
//        AccionesCodigo cod = new AccionesCodigo();
//        cod.loadDatabaseInstances();
//        String codigo = null;
//        for (Shareable s : cod.getEntityInstances()) {
//            codigo = ((Codigo) s).getCodigo_actual_parte_2();
//        }
        return "codigo";
    }

    private String getCodigoReferencia() {
//        AccionesCodigo cod = new AccionesCodigo();
//        cod.loadDatabaseInstances();
//        String codigo = null;
//        for (Shareable s : cod.getEntityInstances()) {
//            codigo = ((Codigo) s).getCodigo_actual_parte_1();
//        }
        return "codigo";
    }

    private String getCodigoApto() {
//        AccionesCodigo cod = new AccionesCodigo();
//        cod.loadDatabaseInstances();
//        String codigo = null;
//        for (Shareable s : cod.getEntityInstances()) {
//            codigo = ((Codigo) s).getCodigo_actual_parte_3();
//        }
        return "codigo";
    }

}
