/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devox.GUI.panels;

import com.devox.GUI.tables.DevoxTableModel;
import com.devox.LOG.Entidades.Configuraciones;
import org.inspira.devox.logger.Log;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import org.inspira.devox.database.DatabaseConnection;
import org.inspira.devox.security.MD5Hash;
import org.inspira.devox.services.BackUp;
import org.inspira.devox.services.other.AccionesCodigo;
import org.inspira.devox.services.signin.AccionesUsers;
import org.inspira.devox.shared.Codigo;
import org.inspira.devox.shared.Shareable;
import org.inspira.devox.shared.Users;
import com.devox.GUI.Cargando;

/**
 *
 * @author azaraf
 */
public class SettingsPanel extends javax.swing.JFrame {

    /**
     * Creates new form Configuraciones
     */
    public SettingsPanel() {
        model = new DevoxTableModel(DevoxTableModel.columnasUsers, new boolean[]{false, false, false});
        
        initComponents();
        ac = new AccionesCodigo();
        ac.loadDatabaseInstances();
        for (Shareable s : ac.getEntityInstances()) {
            fieldRef.setText(((Codigo) s).getCodigo_actual_parte_1());
            fieldDex.setText(((Codigo) s).getCodigo_actual_parte_2());
            fieldApto.setText(((Codigo) s).getCodigo_actual_parte_3());
            fieldDictam.setText(((Codigo) s).getCodigo_actual_parte_4());
            fieldEntreg.setText(((Codigo) s).getCodigo_actual_parte_5());
            fieldTarim.setText(((Codigo) s).getCodigo_actual_parte_6());
        }

        tablaUsuarios();

        Configuraciones conf = new Configuraciones();

        textFieldRoute.setText(conf.getPath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jFrame2 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldRef = new javax.swing.JTextField();
        fieldDex = new javax.swing.JTextField();
        fieldApto = new javax.swing.JTextField();
        fieldDictam = new javax.swing.JTextField();
        fieldEntreg = new javax.swing.JTextField();
        fieldTarim = new javax.swing.JTextField();
        botonAceptarCodificacion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonAceptarUsuarios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        botonAceptarRespaldos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textFieldRoute = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jFrame1.setSize(new java.awt.Dimension(606, 255));

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/group.png"))); // NOI18N
        jLabel7.setText("Nuevo Usuario");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setIconTextGap(24);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel8.setText("Usuario");

        jLabel9.setText("Contraseña");

        jLabel10.setText("Confirmar");

        jButton6.setText("Aceptar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Es un usuario con todos los permisos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(34, 34, 34))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1)
                    .addComponent(jPasswordField2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame2.setSize(new java.awt.Dimension(435, 255));

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/group.png"))); // NOI18N
        jLabel11.setText("Editar Usuario");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setIconTextGap(24);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel12.setText("Usuario");

        jLabel13.setText("Contraseña");

        jLabel14.setText("Confirmar");

        jButton8.setText("Aceptar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Cancelar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Es un usuario con todos los permisos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(34, 34, 34))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jPasswordField3)
                    .addComponent(jPasswordField4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(606, 490));

        jTabbedPane1.setBackground(new java.awt.Color(250, 250, 250));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 534));
        jTabbedPane1.setSize(new java.awt.Dimension(600, 534));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setText("Ref:");

        jLabel2.setText("Cod. en reportes para Destrucción");

        jLabel3.setText("Cod. en reportes para Aptos");

        jLabel4.setText("Cod. en reportes para Dictamen");

        jLabel5.setText("Cod. en reportes para Entregados");

        jLabel6.setText("Cod. en reportes de Tarimas");

        botonAceptarCodificacion.setText("Aceptar");
        botonAceptarCodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarCodificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldRef)
                    .addComponent(fieldDex)
                    .addComponent(fieldApto)
                    .addComponent(fieldDictam)
                    .addComponent(fieldEntreg)
                    .addComponent(fieldTarim, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(botonAceptarCodificacion)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldDex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldDictam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldEntreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldTarim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(botonAceptarCodificacion)
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("Codificación", jPanel1);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        botonAceptarUsuarios.setText("Aceptar");
        botonAceptarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarUsuariosActionPerformed(evt);
            }
        });

        jButton1.setText("Nuevo Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Editar Usuario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptarUsuarios)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(0, 117, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(botonAceptarUsuarios)
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("Usuarios", jPanel2);

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        botonAceptarRespaldos.setText("Aceptar");
        botonAceptarRespaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarRespaldosActionPerformed(evt);
            }
        });

        jButton3.setText("Hacer respaldo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Restaurar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botonAceptarRespaldos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(botonAceptarRespaldos)
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("Respaldos", jPanel3);

        jPanel6.setBackground(new java.awt.Color(250, 250, 250));

        jLabel15.setText("Ruta por defecto");

        textFieldRoute.setEditable(false);

        jButton10.setText("Cambiar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(textFieldRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addContainerGap(438, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PDF", jPanel6);

        jPanel7.setBackground(new java.awt.Color(250, 250, 250));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 80)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(53, 90, 160));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/devox.png"))); // NOI18N
        jLabel16.setText("Devox");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setText("<html>v 1.3.161014.18</html>");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Derechos de autor © 2016 Devox\nCreador por David Azaraf Vargas Baza.\n\nLICENCIA EXCLUSIVA PARA UNA (1) COMPUTADORA DE ABBOTT LABORATORIES DE MÉXICO S.A. DE C.V.\n\nLEA CUIDADOSAMENTE LOS TÉRMINOS Y CONDICIONES DEL PRESENTE DOCUMENTO, ANTES DE LA UTILIZACIÓN DE ESTE PRODUCTO. ESTE CONTIENE SOFTWARE, CUYO USO ES OBJETO DE UNA LICENCIA OTORGADA POR DAVID AZARAF VARGAS BAZA (DE AQUÍ EN ADELANTE DENOMINADO “EL PROGRAMADOR”) A FAVOR DE USTED, EL USUARIO FINAL ORIGINAL ABBOTT LABORATORIES DE MÉXICO S.A. DE C.V (DE AQUÍ EN ADELANTE DENOMINADO “EL CLIENTE”), PARA SU USO EXCLUSIVO COMO SE INDICA. SI USTED NO ESTA DE ACUERDO CON LOS TÉRMINOS Y CONDICIONES DE ESTE CONTRATO, NO UTILICE EL SOFTWARE. EL USO DE CUALQUIER PARTE DEL SOFTWARE INDICA QUE USTED ACEPTA ESTOS TÉRMINOS.\n CLÁUSULA 1. OBJETO. Este acuerdo establece las condiciones de licenciamiento, instalación y uso del programa adquirido Devox (de aquí en adelante denominado “El Software”), software de propiedad exclusiva de David Azaraf Vargas Baza. La licencia objeto del presente acuerdo es concedida exclusivamente para el uso del Cliente.\nCLÁUSULA 2. LICENCIA. El Programador le otorga a usted una licencia limitada, exclusiva, para el uso del software que se acompaña, sujeta a los términos y condiciones recogidos en el presente. No se le permite el uso del software en ninguna otra manera que no esté expresamente autorizada por esta Licencia.\nEl Software es objeto de licencia para su uso en cualquier ordenador personal que disponga el sistema operativo correspondiente para el software adquirido.\nUsted podrá reproducir y usar solo una (1) copia del Software.\nCLÁUSULA 3. DERECHOS DE AUTORÍA. El Software es propiedad exclusiva de David Azaraf Vargas Baza, creador y programador del mismo, y está protegido por la legislación sobre derechos de autor, tratados internacionales y cualquier legislación aplicable. El pago de la licencia otorgada bajo el presente contrato, no constituye la compra del Software ni de los títulos, ni derechos de autor correspondientes. La imagen de “Abbott” y “DHL” usadas en el Software han sido utilizadas únicamente con el objetivo de ilustrar la interfaz gráfica con ánimo de dar identidad al Cliente y usuarios finales del Software.\nCLÁUSULA 4. INSTALACIÓN. El Software, objeto del presente acuerdo será instalado en el equipo de el Cliente. Junto al Software se entrega un manual de usuario final.\nCLÁUSULA 5. DISPOSICIONES GENERALES. El Cliente no deberá usar o alterar el Software con ninguna finalidad, ni podrá utilizar el Software para cualquier otro propósito que el señalado con anterioridad, sin el consentimiento previo por escrito de el Programador, el cual podrá ser denegado por cualquier razón. La modificación, manipulación o alteración en cuanto a ingeniería o recopilación o desmontaje de El Software queda expresamente prohibido.\nEl uso del Software por parte de terceros o para el beneficio de queda expresamente prohibido. El Programador tiene el derecho de invalidar la Licencia del Software en cualquier momento, notificándole al Cliente con sólo un día de anticipación; el Cliente no tendrá derecho a reclamar o solicitar compensación. Igualmente, el Cliente no podrá (a) arrendar o transferir mediante ningún titulo, o incluso por causa sin ánimo de lucro, el uso del Software a terceros; (b) tomar aquellos pasos para, mediante la ingeniería inversa o cualquier otro método, descompilar, desensamblar, analizar o convertir el Software; (c) transferir el Software a otro Equipo, suyo o no. El Cliente se compromete a cumplir estrictamente las instrucciones de El Programador para el uso adecuado del Software.\nCLÁUSULA 6. CONFIDENCIALIDAD. El Software, como también cualquier documentación e información relacionada con éste, son propiedad exclusiva de El Programador. El Cliente conviene en mantener en estricta confidencialidad toda información confidencial que surja del Software, ya que toda la mencionada información es confidencial.\nCLÁUSULA 7. PROPIEDAD. El Software es, y seguirá siendo en todo momento, propiedad de el Programador. El código, diseño de base de datos, algoritmos y lógica de negocio, imagotipo de Devox, interfaz de usuario gráfica y procesos en general del Software son propiedad del Programador. La información usada y tratada por el Software como datos alojados en la propia base de datos son propiedad del Cliente. El Cliente no tendrá ningún derecho, titulo o interés en el Software, y no permitirá que ninguna obligación o gravamen exista sobre éste, ni permitirá el uso del Software por terceros, ni realizará ningún acto que pueda modificar los derechos de autor del Software. Por lo tanto, el Cliente no puede vender, arrendar, prestar, revelar, transmitir o transferir ningún titulo, ni copiar el Software para terceros.\nCLÁUSULA 8. MODIFICACIÓN y ACTUALIZACIÓN DE VERSIONES. El Programador podrá modificar o reinstalar el Software bajo los términos y condiciones incluidos en el presente, reemplazándolo por versiones actualizadas. Habrán tres tipos de actualizaciones (a) actualización de base de datos, la cuál modificará el proceso a nivel base de datos. Estas actualizaciones se harán sobre el manejador de base de datos que utilice el Software; (b) actualización de lógica de negocios, que modificará alguna función o proceso que no implica la alteración del diseño, estructura, funcionamiento o finalidad del software y (c) actualización completa, que altera el diseño, algoritmo, lógica, imagen y/o interacción del Cliente con el Software. Todas las actualizaciones que hagan son a fin de corregir y mejorar el Software para adaptarse a las necesidades del Cliente y cada actualización se hará bajo un costo determinado por el Programador.\nCLÁUSULA 9. DE ASESORÍA TÉCNICA. El Cliente podrá comunicarse vía correo electrónico con el Programador en caso de requerir información acerca del Software, teniendo como plazo máximo para contestar 3 días hábiles a partir de la fecha y hora de recibido. También se podrá comunicar vía telefónica con el Programador agendando previamente la llamada. En caso de requerir soporte o apoyo técnico para solucionar problemas con el software, tendrá un costo a partir del 1 de enero del año 2017. El costo lo definirá el Programador. Si el Cliente requiere de capacitación técnica a usuarios de El Software o visitas físicas al área de operación donde se encuentra la computadora con la instalación, se requerirá cita previa y habrá un costo que definirá el Programador. \nCLÁUSULA 10. RESPONSABILIDAD DEL CLIENTE; RIESGO DE PÉRDIDA. El cliente deberá asumir todo riesgo de pérdida o daño del Software. Asimismo el Programador, no se responsabiliza de ningún daño o pérdida en su ordenador personal derivada del uso de este Software y de los manuales de instrucciones.\nCLÁUSULA 11. ROBO, PERDIDA, O CAMBIO DE ORDENADOR PERSONAL. En caso de robo, pérdida o cambio de su ordenador personal, el Programador no se responsabiliza.\nCLÁUSULA 12. PLAZO Y TERMINACIÓN. Este contrato será efectivo hasta que sea terminado. Usted podrá terminarlo en cualquier momento, mediante la destrucción en cualquier forma del software. También se terminara inmediatamente si usted incumple cualquier termino o condición del presente sin que esto signifique una renuncia de el Programador a su derecho de realizar acciones judiciales que se deriven del mismo.\nCLÁUSULA 13. FACTURACIÓN Y FORMAS DE PAGO. El Programador facturará al cliente por los servicios y/o productos con las tarifas vigentes en cada momento, que serán incrementadas con el IVA correspondiente. El pago se realizará mediante ingreso o transferencia bancaria, siempre por anticipado, no realizándose el suministro o prestación del servicio correspondiente hasta la confirmación efectiva del mismo.\nCLÁUSULA 14. CONTRATO INTEGRAL. Este acuerdo de licencia constituye el contrato completo entre el Cliente y el Programador, reemplaza cualquier acuerdo anterior o actual entre las partes. Este acuerdo no puede ser enmendado, modificado ni ratificado, excepto mediante documento por escrito firmado por ambas partes.\n--------------------------------------------------------------------\n******************************** LICENCIAS DE TERCEROS ********************************\n--------------------------------------------------------------------\n\n======================================================\n                                                       Apache License\n                                              Version 2.0, January 2004\n                                          http://www.apache.org/licenses/\n \n   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n\n   1. Definitions.\n\n      \"License\" shall mean the terms and conditions for use, reproduction,\n      and distribution as defined by Sections 1 through 9 of this document.\n\n      \"Licensor\" shall mean the copyright owner or entity authorized by\n      the copyright owner that is granting the License.\n\n      \"Legal Entity\" shall mean the union of the acting entity and all\n      other entities that control, are controlled by, or are under common\n      control with that entity. For the purposes of this definition,\n      \"control\" means (i) the power, direct or indirect, to cause the\n      direction or management of such entity, whether by contract or\n      otherwise, or (ii) ownership of fifty percent (50%) or more of the\n      outstanding shares, or (iii) beneficial ownership of such entity.\n\n      \"You\" (or \"Your\") shall mean an individual or Legal Entity\n      exercising permissions granted by this License.\n\n      \"Source\" form shall mean the preferred form for making modifications,\n      including but not limited to software source code, documentation\n      source, and configuration files.\n\n      \"Object\" form shall mean any form resulting from mechanical\n      transformation or translation of a Source form, including but\n      not limited to compiled object code, generated documentation,\n      and conversions to other media types.\n\n      \"Work\" shall mean the work of authorship, whether in Source or\n      Object form, made available under the License, as indicated by a\n      copyright notice that is included in or attached to the work\n      (an example is provided in the Appendix below).\n\n      \"Derivative Works\" shall mean any work, whether in Source or Object\n      form, that is based on (or derived from) the Work and for which the\n      editorial revisions, annotations, elaborations, or other modifications\n      represent, as a whole, an original work of authorship. For the purposes\n      of this License, Derivative Works shall not include works that remain\n      separable from, or merely link (or bind by name) to the interfaces of,\n      the Work and Derivative Works thereof.\n\n      \"Contribution\" shall mean any work of authorship, including\n      the original version of the Work and any modifications or additions\n      to that Work or Derivative Works thereof, that is intentionally\n      submitted to Licensor for inclusion in the Work by the copyright owner\n      or by an individual or Legal Entity authorized to submit on behalf of\n      the copyright owner. For the purposes of this definition, \"submitted\"\n      means any form of electronic, verbal, or written communication sent\n      to the Licensor or its representatives, including but not limited to\n      communication on electronic mailing lists, source code control systems,\n      and issue tracking systems that are managed by, or on behalf of, the\n      Licensor for the purpose of discussing and improving the Work, but\n      excluding communication that is conspicuously marked or otherwise\n      designated in writing by the copyright owner as \"Not a Contribution.\"\n\n      \"Contributor\" shall mean Licensor and any individual or Legal Entity\n      on behalf of whom a Contribution has been received by Licensor and\n      subsequently incorporated within the Work.\n\n   2. Grant of Copyright License. Subject to the terms and conditions of\n      this License, each Contributor hereby grants to You a perpetual,\n      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n      copyright license to reproduce, prepare Derivative Works of,\n      publicly display, publicly perform, sublicense, and distribute the\n      Work and such Derivative Works in Source or Object form.\n\n   3. Grant of Patent License. Subject to the terms and conditions of\n      this License, each Contributor hereby grants to You a perpetual,\n      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n      (except as stated in this section) patent license to make, have made,\n      use, offer to sell, sell, import, and otherwise transfer the Work,\n      where such license applies only to those patent claims licensable\n      by such Contributor that are necessarily infringed by their\n      Contribution(s) alone or by combination of their Contribution(s)\n      with the Work to which such Contribution(s) was submitted. If You\n      institute patent litigation against any entity (including a\n      cross-claim or counterclaim in a lawsuit) alleging that the Work\n      or a Contribution incorporated within the Work constitutes direct\n      or contributory patent infringement, then any patent licenses\n      granted to You under this License for that Work shall terminate\n      as of the date such litigation is filed.\n\n   4. Redistribution. You may reproduce and distribute copies of the\n      Work or Derivative Works thereof in any medium, with or without\n      modifications, and in Source or Object form, provided that You\n      meet the following conditions:\n\n      (a) You must give any other recipients of the Work or\n          Derivative Works a copy of this License; and\n\n      (b) You must cause any modified files to carry prominent notices\n          stating that You changed the files; and\n\n      (c) You must retain, in the Source form of any Derivative Works\n          that You distribute, all copyright, patent, trademark, and\n          attribution notices from the Source form of the Work,\n          excluding those notices that do not pertain to any part of\n          the Derivative Works; and\n\n      (d) If the Work includes a \"NOTICE\" text file as part of its\n          distribution, then any Derivative Works that You distribute must\n          include a readable copy of the attribution notices contained\n          within such NOTICE file, excluding those notices that do not\n          pertain to any part of the Derivative Works, in at least one\n          of the following places: within a NOTICE text file distributed\n          as part of the Derivative Works; within the Source form or\n          documentation, if provided along with the Derivative Works; or,\n          within a display generated by the Derivative Works, if and\n          wherever such third-party notices normally appear. The contents\n          of the NOTICE file are for informational purposes only and\n          do not modify the License. You may add Your own attribution\n          notices within Derivative Works that You distribute, alongside\n          or as an addendum to the NOTICE text from the Work, provided\n          that such additional attribution notices cannot be construed\n          as modifying the License.\n\n      You may add Your own copyright statement to Your modifications and\n      may provide additional or different license terms and conditions\n      for use, reproduction, or distribution of Your modifications, or\n      for any such Derivative Works as a whole, provided Your use,\n      reproduction, and distribution of the Work otherwise complies with\n      the conditions stated in this License.\n\n   5. Submission of Contributions. Unless You explicitly state otherwise,\n      any Contribution intentionally submitted for inclusion in the Work\n      by You to the Licensor shall be under the terms and conditions of\n      this License, without any additional terms or conditions.\n      Notwithstanding the above, nothing herein shall supersede or modify\n      the terms of any separate license agreement you may have executed\n      with Licensor regarding such Contributions.\n\n   6. Trademarks. This License does not grant permission to use the trade\n      names, trademarks, service marks, or product names of the Licensor,\n      except as required for reasonable and customary use in describing the\n      origin of the Work and reproducing the content of the NOTICE file.\n\n   7. Disclaimer of Warranty. Unless required by applicable law or\n      agreed to in writing, Licensor provides the Work (and each\n      Contributor provides its Contributions) on an \"AS IS\" BASIS,\n      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or\n      implied, including, without limitation, any warranties or conditions\n      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A\n      PARTICULAR PURPOSE. You are solely responsible for determining the\n      appropriateness of using or redistributing the Work and assume any\n      risks associated with Your exercise of permissions under this License.\n\n   8. Limitation of Liability. In no event and under no legal theory,\n      whether in tort (including negligence), contract, or otherwise,\n      unless required by applicable law (such as deliberate and grossly\n      negligent acts) or agreed to in writing, shall any Contributor be\n      liable to You for damages, including any direct, indirect, special,\n      incidental, or consequential damages of any character arising as a\n      result of this License or out of the use or inability to use the\n      Work (including but not limited to damages for loss of goodwill,\n      work stoppage, computer failure or malfunction, or any and all\n      other commercial damages or losses), even if such Contributor\n      has been advised of the possibility of such damages.\n\n   9. Accepting Warranty or Additional Liability. While redistributing\n      the Work or Derivative Works thereof, You may choose to offer,\n      and charge a fee for, acceptance of support, warranty, indemnity,\n      or other liability obligations and/or rights consistent with this\n      License. However, in accepting such obligations, You may act only\n      on Your own behalf and on Your sole responsibility, not on behalf\n      of any other Contributor, and only if You agree to indemnify,\n      defend, and hold each Contributor harmless for any liability\n      incurred by, or claims asserted against, such Contributor by reason\n      of your accepting any such warranty or additional liability.\n\n   END OF TERMS AND CONDITIONS\n\n   APPENDIX: How to apply the Apache License to your work.\n\n      To apply the Apache License to your work, attach the following\n      boilerplate notice, with the fields enclosed by brackets \"[]\"\n      replaced with your own identifying information. (Don't include\n      the brackets!)  The text should be enclosed in the appropriate\n      comment syntax for the file format. We also recommend that a\n      file or class name and description of purpose be included on the\n      same \"printed page\" as the copyright notice for easier\n      identification within third-party archives.\n\n   Copyright [yyyy] [name of copyright owner]\n\n   Licensed under the Apache License, Version 2.0 (the \"License\");\n   you may not use this file except in compliance with the License.\n   You may obtain a copy of the License at\n\n       http://www.apache.org/licenses/LICENSE-2.0\n\n   Unless required by applicable law or agreed to in writing, software\n   distributed under the License is distributed on an \"AS IS\" BASIS,\n   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n   See the License for the specific language governing permissions and\n   limitations under the License.\n\n======================================================\n\nJCalendar - v1.4 - 07/09/2011\n\n(C) 1999 - 2011 Kai Toedter\nReleased under GNU Lesser General Public License (see jcalendar-license.txt)\nkai@toedter.com\nwww.toedter.com\n\n======================================================\n\niText - itextpdf 5.5.4\nThis program is free software; you can redistribute it and/or modify\nit under the terms of the GNU Affero General Public License version 3\nas published by the Free Software Foundation with the addition of the\nfollowing permission added to Section 15 as permitted in Section 7(a):\nFOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED BY\nITEXT GROUP. ITEXT GROUP DISCLAIMS THE WARRANTY OF NON INFRINGEMENT\nOF THIRD PARTY RIGHTS\n\n======================================================\n\nMySQL v5.7 by Oracle July 2011\nLicensed software under the version 2 of GNU General Public License (the GPL)\n\n======================================================\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCaretPosition(0);
        jTextArea1.setDragEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Acerca de Devox", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarUsuariosActionPerformed
        dispose();
    }//GEN-LAST:event_botonAceptarUsuariosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HaciendoRespaldo car = new HaciendoRespaldo();
        (new Thread(car)).start();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        RestaurandoRespaldo res = new RestaurandoRespaldo();
        (new Thread(res)).start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void botonAceptarRespaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarRespaldosActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botonAceptarRespaldosActionPerformed

    private void botonAceptarCodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarCodificacionActionPerformed
        ac.setCodigo_actual_parte_1(fieldRef.getText());
        ac.setCodigo_actual_parte_2(fieldDex.getText());
        ac.setCodigo_actual_parte_3(fieldApto.getText());
        ac.setCodigo_actual_parte_4(fieldDictam.getText());
        ac.setCodigo_actual_parte_5(fieldEntreg.getText());
        ac.setCodigo_actual_parte_6(fieldTarim.getText());
        ac.setPosition(1);

        DatabaseConnection db = new DatabaseConnection();
        try {
            Connection con = db.getConnection();
            PreparedStatement stmt = con.prepareStatement("UPDATE Codigo SET Codigo_Referencia = ?,Codigo_Destruccion = ?,Codigo_Apto = ?,Codigo_Dictamen = ?,Codigo_Entregado = ?,Codigo_Tarima = ? where idCodigo = ?");
            stmt.setString(1, fieldRef.getText());
            stmt.setString(2, fieldDex.getText());
            stmt.setString(3, fieldApto.getText());
            stmt.setString(4, fieldDictam.getText());
            stmt.setString(5, fieldEntreg.getText());
            stmt.setString(6, fieldTarim.getText());
            stmt.setInt(7, 1);

            stmt.executeUpdate();

        } catch (SQLException ex) {
            Log.print(ex);
            ex.printStackTrace();
        }
        db.closeConnection();
        dispose();
    }//GEN-LAST:event_botonAceptarCodificacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String us = jTextField1.getText();

        if (Arrays.equals(jPasswordField1.getPassword(), jPasswordField2.getPassword())) {

            boolean pm = jCheckBox1.isSelected();

            users.setName(us);
            users.setPass(new MD5Hash().makeHash(jPasswordField1.getText()).getBytes());
            users.setIsAdmin(pm ? 1 : 0);
            users.alta();
            jFrame1.dispose();
            tablaUsuarios();
        } else {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Desea eliminar definitivamente este usuario?", "Usuario", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int row = model.getTabla().getSelectedRow();
            String us = model.getValueAt(row, 0).toString();
            users = new AccionesUsers();
            users.loadDatabaseInstances();
            for (Shareable s : users.getEntityInstances()) {
                if (((Users) s).getName().equals(us)) {
                    users.setName(((Users) s).getName());
                    users.setPass(((Users) s).getPass());
                    users.baja();
                    break;
                }
            }
            model.removeRow(row);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int row = model.getTabla().getSelectedRow();
        String us = model.getValueAt(row, 0).toString();
        users = new AccionesUsers();
        users.loadDatabaseInstances();
        for (Shareable s : users.getEntityInstances()) {
            if (((Users) s).getName().equals(us)) {
                jFrame2.setVisible(true);
                jTextField2.setText(((Users) s).getName());
                jCheckBox2.setSelected(((Users) s).getIsAdmin() == 1);
                break;
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (Arrays.equals(jPasswordField3.getPassword(), jPasswordField4.getPassword())) {

            boolean pm = jCheckBox2.isSelected();

            users.setName(jTextField2.getText());
            users.setPass(new MD5Hash().makeHash(jPasswordField3.getText()).getBytes());
            users.setIsAdmin(pm ? 1 : 0);
            users.cambio();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jFrame2.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("/"));
        chooser.setDialogTitle("Ruta para guardar PDF");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Configuraciones conf = new Configuraciones();
            conf.setPath(chooser.getSelectedFile().getAbsolutePath());
            textFieldRoute.setText(conf.getPath());
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SettingsPanel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarCodificacion;
    private javax.swing.JButton botonAceptarRespaldos;
    private javax.swing.JButton botonAceptarUsuarios;
    private javax.swing.JTextField fieldApto;
    private javax.swing.JTextField fieldDex;
    private javax.swing.JTextField fieldDictam;
    private javax.swing.JTextField fieldEntreg;
    private javax.swing.JTextField fieldRef;
    private javax.swing.JTextField fieldTarim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField textFieldRoute;
    // End of variables declaration//GEN-END:variables
    private AccionesCodigo ac;
    private AccionesUsers users;
    private DevoxTableModel model;
    private Cargando loading = new Cargando(this);
    
    private void tablaUsuarios() {
        users = new AccionesUsers();
        users.loadDatabaseInstances();
        //jScrollPane2.removeAll();
        model.agregarTabla(jScrollPane2);
        model.getTabla().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Object[][] objs = new Object[users.getEntityInstances().length][3];
        for (int i = 0; i < users.getEntityInstances().length; i++) {
            Users u = ((Users) users.getEntityInstances()[i]);
            objs[i][0] = u.getName();
            objs[i][1] = "******";
            objs[i][2] = (boolean) (u.getIsAdmin() == 1);
        }
        model.llenarDeDatos(objs);
    }
    
    public void hacerRespaldo(){
        BackUp bck = new BackUp();
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.setDialogType(JFileChooser.SAVE_DIALOG);
        jFileChooser1.setSelectedFile(new File("/Respaldo_" + new SimpleDateFormat("yyyy_MM_dd").format(new Date()) + ".sql"));
        if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            loading.personalizarMensaje("Haciendo respaldo en " + jFileChooser1.getSelectedFile().getName());
            bck.crearRespaldo(jFileChooser1.getSelectedFile().getAbsolutePath(), new String[]{"admin", "abbott", "DevoxDB"});
        }
        JOptionPane.showMessageDialog(null, "Respaldo guardado!");
        loading.removeLoadingPanel();
    }
    
    public void restaurarRespaldo(){
        BackUp bck = new BackUp();
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.setDialogType(JFileChooser.OPEN_DIALOG);
        if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            loading.personalizarMensaje("Restaurando el respaldo " + jFileChooser1.getSelectedFile().getName());
            bck.restaurarBackUp(jFileChooser1.getSelectedFile().getAbsolutePath());
        }
        JOptionPane.showMessageDialog(null, "Respaldo hecho! Reinicie Devox");
        loading.removeLoadingPanel();
    }
    private class HaciendoRespaldo implements Runnable{

        @Override
        public void run() {
            (new Thread(new Loading())).start();
            try{new Thread().sleep(500);} catch (InterruptedException e) {}
            hacerRespaldo();
        }
        
    }
    
    private class RestaurandoRespaldo implements Runnable{

        @Override
        public void run() {
            (new Thread(new Loading())).start();
            try{new Thread().sleep(500);} catch (InterruptedException e) {}
            restaurarRespaldo();
        }
        
    }
    
    class Loading implements Runnable{

        @Override
        public void run() {
            loading.setLoadingPanel();
        }
         
    }
}
