/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devox.GUI.panels;

import com.devox.GUI.Cargando;
import com.devox.GUI.PDF.CrearReportePrincipal;
import com.devox.GUI.PDF.ReporteRMA;
import com.devox.GUI.PDF.VerReportePrincipal;
import static com.devox.GUI.panels.VerDevoluciones.captura;
import static com.devox.GUI.panels.VerDevoluciones.dictamen;
import static com.devox.GUI.panels.VerDevoluciones.entregado;
import static com.devox.GUI.panels.VerDevoluciones.segregacion;
import com.devox.LOG.cuadricula.ListaCuadriculas;
import java.awt.Color;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.inspira.devox.logger.Log;
import org.inspira.devox.services.devolucion.AccionesDescripcionDevolucion;
import org.inspira.devox.services.devolucion.AccionesDescripcionDevolucionEstado;
import org.inspira.devox.services.queries.ReportePorEstadoDeFolio;

/**
 *
 * @author azaraf
 */
public class VerReportes extends javax.swing.JPanel {

    private int quantityHoy;
    private int quantitySemana;
    private int quantityMes;
    private AccionesDescripcionDevolucion descripcion;
    private AccionesDescripcionDevolucionEstado detallesEstado;
    private Cargando loading;

    /**
     * Creates new form VerDevoluciones
     * @param frame
     */
    public VerReportes(JFrame frame) {
        initComponents();
        loading = new Cargando(frame);
        botonSelectAll1.setVisible(false);
        botonSelectAll2.setVisible(false);
        botonSelectAll3.setVisible(false);
        botonUnSelectAll1.setVisible(false);
        botonUnSelectAll2.setVisible(false);
        botonUnSelectAll3.setVisible(false);
        botonSelectRange1.setVisible(false);
        botonSelectRange2.setVisible(false);
        botonSelectRange3.setVisible(false);

        descripcion = new AccionesDescripcionDevolucion();
        descripcion.loadDatabaseInstances();
        detallesEstado = new AccionesDescripcionDevolucionEstado();
        detallesEstado.loadDatabaseInstances();
        //sucursal = new FolioJoinSursal();
        //sucursal.loadDatabaseInstances();
        quantityHoy = (Integer) spinnerHoy.getValue();
        quantitySemana = (Integer) spinnerSemana.getValue();
        quantityMes = (Integer) spinnerMes.getValue();

        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(20);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane2.getHorizontalScrollBar().setUnitIncrement(20);
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane3.getHorizontalScrollBar().setUnitIncrement(20);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(20);

        segregacion = ListaDeDevoluciones.getCantidadSegregados();
        labelSegregacion.setText(String.valueOf(segregacion));
        dictamen = ListaDeDevoluciones.getCantidadDictaminados();
        labelDictamen.setText(String.valueOf(dictamen));
        captura = ListaDeDevoluciones.getCantidadCapturados();
        labelCaptura.setText(String.valueOf(captura));
        entregado = ListaDeDevoluciones.getCantidadEntregados();
        labelEntregado.setText(String.valueOf(entregado));

        CargandoDevoluciones c = new CargandoDevoluciones();
        (new Thread(c)).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elegirFecha2 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        botonOk2 = new javax.swing.JButton();
        hasta2 = new com.toedter.calendar.JDateChooser();
        desde2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        elegirFecha = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        desde1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hasta1 = new com.toedter.calendar.JDateChooser();
        botonOK1 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        estadisticasOKButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelHoy = new javax.swing.JPanel();
        botonSelectAll1 = new javax.swing.JButton();
        botonUnSelectAll1 = new javax.swing.JButton();
        botonSelectRange1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        spinnerHoy = new javax.swing.JSpinner();
        panel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelSem = new javax.swing.JPanel();
        botonSelectAll2 = new javax.swing.JButton();
        botonUnSelectAll2 = new javax.swing.JButton();
        botonSelectRange2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        spinnerSemana = new javax.swing.JSpinner();
        panel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelMes = new javax.swing.JPanel();
        botonSelectAll3 = new javax.swing.JButton();
        botonUnSelectAll3 = new javax.swing.JButton();
        botonSelectRange3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        spinnerMes = new javax.swing.JSpinner();
        panel4 = new javax.swing.JPanel();
        panelPersonalizar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        botonExcel = new javax.swing.JLabel();
        botonTxt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelCaptura = new javax.swing.JLabel();
        labelDictamen = new javax.swing.JLabel();
        labelSegregacion = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelEntregado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        elegirFecha2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        elegirFecha2.setTitle("Seleccione rango de fechas");
        elegirFecha2.setBackground(new java.awt.Color(250, 250, 250));
        elegirFecha2.setMinimumSize(new java.awt.Dimension(320, 180));
        elegirFecha2.setSize(new java.awt.Dimension(320, 180));

        botonOk2.setText("OK");
        botonOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOk2ActionPerformed(evt);
            }
        });

        jLabel1.setText("De:");

        jLabel2.setText("A:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(288, Short.MAX_VALUE)
                        .addComponent(botonOk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desde2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(desde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(hasta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 55, Short.MAX_VALUE)
                .addComponent(botonOk2))
        );

        javax.swing.GroupLayout elegirFecha2Layout = new javax.swing.GroupLayout(elegirFecha2.getContentPane());
        elegirFecha2.getContentPane().setLayout(elegirFecha2Layout);
        elegirFecha2Layout.setHorizontalGroup(
            elegirFecha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        elegirFecha2Layout.setVerticalGroup(
            elegirFecha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setSelectedFile(new java.io.File("/" + "ReportePrincipal.txt"));

        elegirFecha.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        elegirFecha.setTitle("Seleccione rango de fechas");
        elegirFecha.setBackground(new java.awt.Color(250, 250, 250));
        elegirFecha.setMinimumSize(new java.awt.Dimension(320, 180));
        elegirFecha.setSize(new java.awt.Dimension(320, 180));

        jLabel3.setText("De:");

        jLabel4.setText("A:");

        botonOK1.setText("OK");
        botonOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOK1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonOK1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desde1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hasta1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(desde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(hasta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonOK1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout elegirFechaLayout = new javax.swing.GroupLayout(elegirFecha.getContentPane());
        elegirFecha.getContentPane().setLayout(elegirFechaLayout);
        elegirFechaLayout.setHorizontalGroup(
            elegirFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elegirFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        elegirFechaLayout.setVerticalGroup(
            elegirFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elegirFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame1.setMinimumSize(new java.awt.Dimension(371, 109));
        jFrame1.setSize(new java.awt.Dimension(370, 120));

        jPanel6.setPreferredSize(new java.awt.Dimension(341, 120));

        jLabel18.setText("De:");

        jLabel19.setText("Hasta:");

        estadisticasOKButton.setText("OK");
        estadisticasOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estadisticasOKButton)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(estadisticasOKButton))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(250, 250, 250));
        setMinimumSize(new java.awt.Dimension(720, 1600));
        setPreferredSize(new java.awt.Dimension(720, 1600));
        setLayout(new java.awt.GridLayout(4, 1, 10, 3));

        panel1.setBackground(new java.awt.Color(250, 250, 250));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoy", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(50, 50, 50))); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(720, 300));

        panelHoy.setBackground(new java.awt.Color(250, 250, 250));
        panelHoy.setLayout(new java.awt.GridLayout(0, 1, 5, 10));
        jScrollPane1.setViewportView(panelHoy);

        botonSelectAll1.setText("Seleccionar todos");
        botonSelectAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSelectAll1ActionPerformed(evt);
            }
        });

        botonUnSelectAll1.setText("Deseleccionar todos");
        botonUnSelectAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnSelectAll1ActionPerformed(evt);
            }
        });

        botonSelectRange1.setText("Seleccionar por rango");
        botonSelectRange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSelectRange1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Ver últimos");

        spinnerHoy.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinnerHoy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHoyStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(botonSelectAll1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonUnSelectAll1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSelectRange1)
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 156, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(spinnerHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonSelectAll1)
                        .addComponent(botonUnSelectAll1)
                        .addComponent(botonSelectRange1))))
        );

        add(panel1);

        panel2.setBackground(new java.awt.Color(250, 250, 250));
        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Esta semana", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(50, 50, 50))); // NOI18N
        panel2.setPreferredSize(new java.awt.Dimension(720, 300));

        panelSem.setBackground(new java.awt.Color(250, 250, 250));
        panelSem.setLayout(new java.awt.GridLayout(0, 1, 5, 10));
        jScrollPane2.setViewportView(panelSem);

        botonSelectAll2.setText("Seleccionar todos");
        botonSelectAll2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSelectAll2ActionPerformed(evt);
            }
        });

        botonUnSelectAll2.setText("Deseleccionar todos");
        botonUnSelectAll2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnSelectAll2ActionPerformed(evt);
            }
        });

        botonSelectRange2.setText("Seleccionar por rango");
        botonSelectRange2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSelectRange2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Ver últimos");

        spinnerSemana.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinnerSemana.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerSemanaStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(botonSelectAll2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonUnSelectAll2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSelectRange2)
                .addGap(122, 122, 122)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(spinnerSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonSelectAll2)
                        .addComponent(botonUnSelectAll2)
                        .addComponent(botonSelectRange2))))
        );

        add(panel2);

        panel3.setBackground(new java.awt.Color(250, 250, 250));
        panel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Este mes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(50, 50, 50))); // NOI18N
        panel3.setPreferredSize(new java.awt.Dimension(720, 300));

        panelMes.setBackground(new java.awt.Color(250, 250, 250));
        panelMes.setLayout(new java.awt.GridLayout(0, 1, 5, 10));
        jScrollPane3.setViewportView(panelMes);

        botonSelectAll3.setText("Seleccionar todos");
        botonSelectAll3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSelectAll3ActionPerformed(evt);
            }
        });

        botonUnSelectAll3.setText("Deseleccionar todos");
        botonUnSelectAll3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnSelectAll3ActionPerformed(evt);
            }
        });

        botonSelectRange3.setText("Seleccionar por rango");

        jLabel13.setText("Ver últimos");

        spinnerMes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinnerMes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerMesStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addComponent(botonSelectAll3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonUnSelectAll3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSelectRange3)
                .addGap(122, 122, 122)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonSelectAll3)
                        .addComponent(botonUnSelectAll3)
                        .addComponent(botonSelectRange3))))
        );

        add(panel3);

        panel4.setBackground(new java.awt.Color(250, 250, 250));
        panel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Características específicas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        panel4.setPreferredSize(new java.awt.Dimension(720, 300));

        panelPersonalizar.setBackground(new java.awt.Color(250, 250, 250));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte Principal"));

        jButton2.setText("Ver reporte principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botonExcel.setBackground(new java.awt.Color(250, 250, 250));
        botonExcel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/excel.png"))); // NOI18N
        botonExcel.setText("<html><div align=\"center\">Exportar reporte principal en Excel</div></html>");
        botonExcel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonExcel.setIconTextGap(8);
        botonExcel.setOpaque(true);
        botonExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExcelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonExcelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonExcelMouseEntered(evt);
            }
        });

        botonTxt.setBackground(new java.awt.Color(250, 250, 250));
        botonTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devox/GUI/images/txt.png"))); // NOI18N
        botonTxt.setText("<html><div align=\"center\">Exportar reporte principal en TXT</html>");
        botonTxt.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTxt.setIconTextGap(8);
        botonTxt.setOpaque(true);
        botonTxt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTxtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonTxtMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonTxtMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadísticas"));

        jLabel5.setText("REPORTES POR DÍA");

        jLabel6.setText("jLabel6");

        jLabel7.setText("REPORTES POR SEMANA");

        jLabel8.setText("REPORTES POR MES");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadísticas -Todo-"));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(50, 50, 50));
        jLabel14.setText("Segregación");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(9, 92, 173));
        jLabel15.setText("Dictamen");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 102));
        jLabel16.setText("Captura DLX");

        labelCaptura.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelCaptura.setForeground(new java.awt.Color(255, 102, 102));
        labelCaptura.setText("0");

        labelDictamen.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelDictamen.setForeground(new java.awt.Color(9, 92, 173));
        labelDictamen.setText("0");

        labelSegregacion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelSegregacion.setForeground(new java.awt.Color(50, 50, 50));
        labelSegregacion.setText("0");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 204, 0));
        jLabel17.setText("Entregado");

        labelEntregado.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelEntregado.setForeground(new java.awt.Color(102, 204, 0));
        labelEntregado.setText("0");

        jButton1.setText("Seleccionar rango de fecha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(labelDictamen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSegregacion, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(labelCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(labelEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelSegregacion)
                        .addComponent(jButton1))
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDictamen)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCaptura)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(labelEntregado))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPersonalizarLayout = new javax.swing.GroupLayout(panelPersonalizar);
        panelPersonalizar.setLayout(panelPersonalizarLayout);
        panelPersonalizarLayout.setHorizontalGroup(
            panelPersonalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPersonalizarLayout.setVerticalGroup(
            panelPersonalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPersonalizarLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPersonalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addComponent(panelPersonalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panel4);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSelectAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSelectAll1ActionPerformed
        seleccionarTodos(listaHoy, true);
    }//GEN-LAST:event_botonSelectAll1ActionPerformed

    private void botonUnSelectAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnSelectAll1ActionPerformed
        seleccionarTodos(listaHoy, false);
    }//GEN-LAST:event_botonUnSelectAll1ActionPerformed

    private void botonSelectRange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSelectRange1ActionPerformed
        elegirFecha2.setVisible(true);
    }//GEN-LAST:event_botonSelectRange1ActionPerformed

    private void botonOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOk2ActionPerformed
        Date desde = desde2.getDate();
        Date hasta = hasta2.getDate();
        int type = 0;
        if (isText) {
            jFileChooser1.setSelectedFile(new java.io.File("/" + "ReportePrincipal.txt"));
            type = 1;
            isText = false;
        }
        if (isCsv) {
            jFileChooser1.setSelectedFile(new java.io.File("/" + "ReportePrincipal.csv"));
            isCsv = false;
        }
        elegirFecha2.setVisible(false);
        if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                if (type == 1) {
                    ReporteRMA reporte = new ReporteRMA(desde, hasta);
                    reporte.crear(jFileChooser1.getSelectedFile());
                    type = 0;
                } else {
                    CrearReportePrincipal reporte = new CrearReportePrincipal(desde, hasta);
                    reporte.crear(jFileChooser1.getSelectedFile());
                }

            } catch (IOException ex) {
                if (ex.getMessage().contains("Permission")) {
                    JOptionPane.showMessageDialog(null, "No se puede guardar el archivo en esta ubicación\nporque no tiene permiso. Intente guardarlo en otra ubicación");
                }
                Log.print(ex);
            }
        } else {
            Log.print("No se guardó el Reporte principal");
        }

    }//GEN-LAST:event_botonOk2ActionPerformed

    private void botonSelectAll2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSelectAll2ActionPerformed
        seleccionarTodos(listaSem, true);
    }//GEN-LAST:event_botonSelectAll2ActionPerformed

    private void botonExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExcelMouseEntered
        botonExcel.setBackground(Color.lightGray);
    }//GEN-LAST:event_botonExcelMouseEntered

    private void botonExcelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExcelMouseExited
        botonExcel.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_botonExcelMouseExited

    private void botonTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTxtMouseEntered
        botonTxt.setBackground(Color.lightGray);
    }//GEN-LAST:event_botonTxtMouseEntered

    private void botonTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTxtMouseExited
        botonTxt.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_botonTxtMouseExited

    private void botonExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExcelMouseClicked
        elegirFecha2.setVisible(true);
        elegirFecha2.setLocationRelativeTo(null);
        isCsv = true;
    }//GEN-LAST:event_botonExcelMouseClicked

    private void botonTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTxtMouseClicked
        elegirFecha2.setVisible(true);
        elegirFecha2.setLocationRelativeTo(null);
        isText = true;
    }//GEN-LAST:event_botonTxtMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        elegirFecha.setVisible(true);
        elegirFecha.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOK1ActionPerformed
        elegirFecha.setVisible(false);
        viewReportePrincipalTable(desde1.getDate(), hasta1.getDate());
    }//GEN-LAST:event_botonOK1ActionPerformed

    private void botonUnSelectAll2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnSelectAll2ActionPerformed
        seleccionarTodos(listaSem, false);
    }//GEN-LAST:event_botonUnSelectAll2ActionPerformed

    private void botonSelectRange2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSelectRange2ActionPerformed
        elegirFecha.setVisible(true);
    }//GEN-LAST:event_botonSelectRange2ActionPerformed

    private void spinnerHoyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHoyStateChanged
        // TODO add your handling code here:
        quantityHoy = (Integer) spinnerHoy.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        Date today = new Date();
        Calendar hoy = Calendar.getInstance();
        hoy.setTime(today);
        //Hoy
        //System.out.println("Mes: desde " + sdf.format(today) + " hasta " + sdf.format(today));
        ListaCuadriculas.getLastDevolucionesPorFechas(listaHoy, (today), (today), quantityHoy);
        llenarPanel(panelHoy, listaHoy, quantityHoy);
    }//GEN-LAST:event_spinnerHoyStateChanged

    private void spinnerSemanaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerSemanaStateChanged
        // TODO add your handling code here:
        quantitySemana = (Integer) spinnerSemana.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        Calendar devo1 = Calendar.getInstance();
        Calendar devo2 = Calendar.getInstance();
        devo1.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        devo2.set(Calendar.DAY_OF_WEEK, Calendar.SUNDAY);
        ListaCuadriculas.getLastDevolucionesPorFechas(listaSem, (devo1.getTime()), (devo2.getTime()), quantitySemana);
        llenarPanel(panelSem, listaSem, quantitySemana);
    }//GEN-LAST:event_spinnerSemanaStateChanged

    private void spinnerMesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerMesStateChanged
        // TODO add your handling code here:
        quantityMes = (Integer) spinnerMes.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        Calendar devo1 = Calendar.getInstance();
        Calendar devo2 = Calendar.getInstance();
        devo1.set(Calendar.DAY_OF_MONTH, 1);
        devo2.set(Calendar.DAY_OF_MONTH, devo2.getActualMaximum(Calendar.DAY_OF_MONTH));
        ListaCuadriculas.getLastDevolucionesPorFechas(listaMes, (devo1.getTime()), (devo2.getTime()), quantityMes);
        llenarPanel(panelMes, listaMes, quantityMes);
    }//GEN-LAST:event_spinnerMesStateChanged

    private void botonSelectAll3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSelectAll3ActionPerformed
        // TODO add your handling code here:
        seleccionarTodos(listaMes, true);
    }//GEN-LAST:event_botonSelectAll3ActionPerformed

    private void botonUnSelectAll3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnSelectAll3ActionPerformed
        // TODO add your handling code here:
        seleccionarTodos(listaMes, false);
    }//GEN-LAST:event_botonUnSelectAll3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void estadisticasOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasOKButtonActionPerformed
        // TODO add your handling code here:

        Date desde = jDateChooser1.getDate();
        Date hasta = jDateChooser2.getDate();
        jFrame1.dispose();
        porFechas(desde, hasta);
    }//GEN-LAST:event_estadisticasOKButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonExcel;
    private javax.swing.JButton botonOK1;
    private javax.swing.JButton botonOk2;
    private javax.swing.JButton botonSelectAll1;
    private javax.swing.JButton botonSelectAll2;
    private javax.swing.JButton botonSelectAll3;
    private javax.swing.JButton botonSelectRange1;
    private javax.swing.JButton botonSelectRange2;
    private javax.swing.JButton botonSelectRange3;
    private javax.swing.JLabel botonTxt;
    private javax.swing.JButton botonUnSelectAll1;
    private javax.swing.JButton botonUnSelectAll2;
    private javax.swing.JButton botonUnSelectAll3;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser desde1;
    private com.toedter.calendar.JDateChooser desde2;
    private javax.swing.JFrame elegirFecha;
    private javax.swing.JFrame elegirFecha2;
    private javax.swing.JButton estadisticasOKButton;
    private com.toedter.calendar.JDateChooser hasta1;
    private com.toedter.calendar.JDateChooser hasta2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JLabel labelCaptura;
    private static javax.swing.JLabel labelDictamen;
    private static javax.swing.JLabel labelEntregado;
    private static javax.swing.JLabel labelSegregacion;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panelHoy;
    private javax.swing.JPanel panelMes;
    private javax.swing.JPanel panelPersonalizar;
    private javax.swing.JPanel panelSem;
    private javax.swing.JSpinner spinnerHoy;
    private javax.swing.JSpinner spinnerMes;
    private javax.swing.JSpinner spinnerSemana;
    // End of variables declaration//GEN-END:variables
    List<CuadriculaLista> listaMes = new ArrayList<>();
    List<CuadriculaLista> listaSem = new ArrayList<>();
    List<CuadriculaLista> listaPersonalizada = new ArrayList<>();
    List<CuadriculaLista> listaHoy = new ArrayList<>();

    boolean isText = false;
    boolean isCsv = false;

    private void llenarDatos() {
        Date today = new Date();
        Calendar hoy = Calendar.getInstance();
        hoy.setTime(today);
        Calendar devo1 = Calendar.getInstance();
        Calendar devo2 = Calendar.getInstance();
        
        //Hoy
        ListaCuadriculas.getLastDevolucionesPorFechas(listaHoy, (today), (today), quantityHoy);
        
        //Esta semana
        devo1.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        devo2.set(Calendar.DAY_OF_WEEK, Calendar.SUNDAY);
        ListaCuadriculas.getLastDevolucionesPorFechas(listaSem, (devo1.getTime()), (devo2.getTime()), quantitySemana);
        
        //Este mes
        devo1.set(Calendar.DAY_OF_MONTH, 1);
        devo2.set(Calendar.DAY_OF_MONTH, devo2.getActualMaximum(Calendar.DAY_OF_MONTH));
        ListaCuadriculas.getLastDevolucionesPorFechas(listaMes, (devo1.getTime()), (devo2.getTime()), quantityMes);
        
        jLabel6.setText("" + listaHoy.size());
        jLabel9.setText("" + listaSem.size());
        jLabel10.setText("" + listaMes.size());
    }

    private void llenarPanel(JPanel panel, List<CuadriculaLista> lista, int quantity) {
        panel.removeAll();
        int limit = lista.size();
        if (limit >= quantity) {
            for (int i = limit - 1; i >= limit - quantity; i--) {
                CuadriculaLista c = lista.get(i);
                c.crearCuadricula();
                panel.add(c);
            }
        } else {
            for (int i = limit - 1; i >= 0; i--) {
                CuadriculaLista c = lista.get(i);
                c.crearCuadricula();
                panel.add(c);
            }
        }
        panel.revalidate();
        panel.repaint();
    }

    private void seleccionarTodos(List<CuadriculaLista> lista, boolean what) {
        for (CuadriculaLista c : lista) {
            c.setjCheckBox1(what);
            c.revalidate();
            c.repaint();
        }

    }

    private void viewReportePrincipalTable(Date desde, Date hasta) {
        JFrame frame = new JFrame("Reporte principal - Vista");
        VerReportePrincipal ver = new VerReportePrincipal(desde, hasta);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        ver.setOpaque(true);
        frame.setContentPane(ver);
        frame.pack();
        frame.setVisible(true);
    }

    private void porFechas(Date desde, Date hasta) {
        ReportePorEstadoDeFolio rep = new ReportePorEstadoDeFolio();
        List<List<String>> lista = rep.obtenerCantidadDeFoliosEnEstadoPorFechas(desde.getTime(), hasta.getTime());
        labelSegregacion.setText("0");
        labelDictamen.setText("0");
        labelCaptura.setText("0");
        labelEntregado.setText("0");

        for (List<String> fila : lista) {
            String cant = fila.get(0);
            switch (fila.get(1)) {
                case "Segregación":
                    labelSegregacion.setText(cant);
                    break;

                case "Dictamen":
                    labelDictamen.setText(cant);
                    break;

                case "Captura DLX":
                    labelCaptura.setText(cant);
                    break;

                case "Entregado":
                    labelEntregado.setText(cant);
                    break;
            }
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadísticas -del " + sdf.format(desde) + " al " + sdf.format(hasta) + "-"));
    }
    
    private void llenarFirst(){
        llenarPanel(panelHoy, listaHoy, quantityHoy);
        llenarPanel(panelSem, listaSem, quantityMes);
        llenarPanel(panelMes, listaMes, quantityMes);
        loading.removeLoadingPanel();
    }

    class CargandoDevoluciones implements Runnable {

        @Override
        public void run() {
            (new Thread(new Loading())).start();
            try {
                new Thread().sleep(500);
            } catch (InterruptedException e) {
            }
            llenarDatos();
            llenarFirst();
        }
    }

    class Loading implements Runnable {

        @Override
        public void run() {
            loading.setLoadingPanel();
        }
    }
}
